### ISSUE TITLE
Request: separate files for each scroll-lock toggle

### ISSUE THREAD

**Issue by jarredwalton** [GameTechDev/PresentMon#10]
Right now, all data appears to get captured into a single monolithic file. That's great for some, but if you want to test different settings/areas, it doesn't really work well. I'm not looking to get into coding, but can I request someone add a feature to create a new file each time scroll-lock is activated? Ideally, PresentMon shouldn't start writing to any file until it's actively counting frames, at least if the -scroll_toggle option is passed to it. Then it would be easier to open a new file, start writing data, and stop when finished.

Thanks for reading; I have no idea if anyone will pay attention. You can email me if you want to talk about this (look up Jarred Walton on PC Gamer if you need an address).

**Comment by dbregman** [comment]
Implemented in build 106 via the F11 hotkey toggle mode. It creates a separate file for each toggle.
