### ISSUE TITLE
Crash when using PresentMon64.exe

### ISSUE THREAD

**Issue by jarredwalton** [GameTechDev/PresentMon#11]
I'm using the latest build, and I'm getting an error when trying to use it with Hitman 47:

Assertion failed: !p->Completed, file PresentMonEtw.cpp, line 243

Test system has a GTX 980 Ti with 364.72 drivers. Not sure if that matters, but I'll look into it. Possibly Hitman is already monitoring things with the built-in benchmarking utility as well.

**Comment by dbregman** [comment]
Is your issue solved using the -simple switch in build 105?

**Comment by jarredwalton** [comment]
Hey, finally got around to trying this. The -simple switch does appear to have fixed the periodic crashing I was experiencing with PresentMon -- not just this specific error, but I had crashes in other stuff as well. Thanks!
