### ISSUE TITLE
No specified event record in EventRecordCallback

### ISSUE THREAD

**Issue by stephen9357** [GameTechDev/PresentMon#110]
I built Debug | x64 version with SDK 10.0.22000.0, in VS2022 Community, it only shows `** RECORDING **`.

I tried set breakpoint in all `HandleXXEvent` functions, but hit nothing.

What should I do to resolve this problem? Thanks.

**Comment by JeffersonMontgomery-Intel** [comment]
Not sure if this is potentially a build or system issue or something else.  Does the release build collect data on your pc?

https://github.com/GameTechDev/PresentMon/releases/tag/v1.7.0

**Comment by stephen9357** [comment]
> Not sure if this is potentially a build or system issue or something else. Does the release build collect data on your pc?
> 
> https://github.com/GameTechDev/PresentMon/releases/tag/v1.7.0

No, it only shows "** RECORDING **" too.

Both my build and release build works on another Windows 10, maybe depends on system service or something else? Can you give me more advice to address this problem? Thanks.

**Comment by JeffersonMontgomery-Intel** [comment]
Perhaps the first thing to check is if you're sure there's a graphics application running on that PC making presents?

**Comment by stephen9357** [comment]
@JeffersonMontgomery-Intel Thanks for you reply.
Yes, I can confirm it. I am running CS:GO, this game can the real FPS by itself, I an trying compare the two results.

**Comment by liwengithub** [comment]
same question，
some pc work well，some not work，it only shows "** RECORDING **" too.
any advice？

**Comment by JeffersonMontgomery-Intel** [comment]
If possible, could you share a short ETW log capture from one of these systems?

See here for instructions: https://github.com/GameTechDev/PresentMon/blob/main/CONTRIBUTING.md#requesting-features-and-reporting-issues

**Comment by liwengithub** [comment]
Strange things happen。。。
in the not working pc，i try this cmd:"Xperf.exe -start CaptureState -on 802ec45a-1e99-4b83-9920-87c98277ba9d"
and then,PresentMon-1.7.0-x86.exe start working! output:"csgo.exe 60fps"
i think i find some key ,but i don't understand why

**Comment by liwengithub** [comment]
TraceSession.cpp: 
ULONG EnableProviders(
    TRACEHANDLE sessionHandle,
    GUID const& sessionGuid,
    PMTraceConsumer* pmConsumer,
    MRTraceConsumer* mrConsumer)
{
....
allKeywordMask = anyKeywordMask;
->
allKeywordMask = 0;


all my pc work
