### ISSUE TITLE
Regression: Only DWM appears in PresentMon output

### ISSUE THREAD

**Issue by cgutman** [GameTechDev/PresentMon#114]
When building the latest code from main (c80abeb) to test the fix for #112, I noticed that no applications were showing up in the trace. Only DWM itself appears in the output on my system now. This is the case both running as admin and as a normal user.

![image](https://user-images.githubusercontent.com/2695644/170394819-5d2bb484-e0da-4419-8783-809b7c8879b9.png)

I bisected the issue locally and it appears to be caused by 9eb75c1e227e16de770557a976c73e3b251f8efc.

My system is:
NVIDIA Quadro P400
NVIDIA Quadro Desktop driver version 512.78
3 2560x1440 60 Hz monitors
Windows 11 22000

I can grab an ETL trace if you want or whatever else you need.

**Comment by JeffersonMontgomery-Intel** [comment]
Hmmm, sorry about that.  I only tested it on Win10.  On Win11 I'm seeing:
- DX12 (DXGI): works
- DX9: DWM only
- VK: DWM only

I'll take a look...

**Comment by cgutman** [comment]
Yep, looks fixed for me too

**Comment by JeffersonMontgomery-Intel** [comment]
Good to hear; sorry about that!
