### ISSUE TITLE
Can I use your software to measure the latency on a screen caster?

### ISSUE THREAD

**Issue by bluetooth12** [GameTechDev/PresentMon#117]
Hi,
I'm trying to build a screen caster and would like to measure the latency on what I have (i.e. the time between an image appearing on one monitor/computer and then appearing on another monitor/computer)? Can I use your software to do that?

**Comment by JeffersonMontgomery-Intel** [comment]
Not directly.  You can run PresentMon on both computers to measure the latency from each computer's Present()-to-screen.  But you'll need some extra way to associate the frames between the two.  e.g., if you have an ID for each frame and measure when your software presents that ID on each computer, then you should be able to cross-reference all the data.
