### ISSUE TITLE
flush stdout immediately when use -output_stdout option

### ISSUE THREAD

**Issue by agier9** [GameTechDev/PresentMon#120]
I am trying to redirect presentMon's stdout to get its output in my exe. But as stdout flushes once the buffer is full, data got in my exe side delayed. Also one line data may be broken into two.

So, I am wondering if you could flush stdout immediately after each 'fprinft'. that's to say just add the following code at the bottom of function 'UpdateCsv' in file 'presentMon/CsvOutput.cpp'.
`if (args.mOutputCsvToStdout) {
        fflush(stdout);
    }`

**Comment by JeffersonMontgomery-Intel** [comment]
Added to main branch.
