### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by Rainnny7** [GameTechDev/PresentMon#128]
This piece of shit idles at like 4.5gb of ram, please improve

**Comment by JeffersonMontgomery-Intel** [comment]
Not able to reproduce.  Please provide more details on what you are doing.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/33905536/213317913-02dfe5de-7ea2-4cfb-9f63-c885015f8b0f.png">

**Comment by Zero3K** [comment]
![image](https://github.com/GameTechDev/PresentMon/assets/6194332/0611814c-3fb4-4328-9515-c7efc29c3fca)

**Comment by Zero3K** [comment]
Its Private Bytes usage needs improving though.

**Comment by JeffersonMontgomery-Intel** [comment]
why?

**Comment by Zero3K** [comment]
Its over 20 MB.

**Comment by JeffersonMontgomery-Intel** [comment]
I see that, why does it need to be less than 20 MB?  If you want me to work on an issue for you, you'll need to motivate why it is important.

**Comment by Rainnny7** [comment]
this is tragic

**Comment by jonckennedy** [comment]
Why is it tragic? The presentmon Dev has asked a perfectly valid question
to help prioritise work. 20mb sounds awesome tbh - not many apps use such a
small amount.

What is your use-case - genuinely interested?
