### ISSUE TITLE
How Is PC Latency Calculated in FrameView?

### ISSUE THREAD

**Issue by amitxv** [GameTechDev/PresentMon#129]
PC Latency is exclusive to FrameView and NVIDIA seem to be using a proprietary PresentMon binary so the formula used is obviously unknown. Is there any formula we can use with the regular binary released on this repository to get similar data (calculate render and gpu latency)?

As I understand, [Measuring Application Latency](https://github.com/GameTechDev/PresentMon#measuring-application-latency) is only the Game Latency in the diagram below.

![image](https://user-images.githubusercontent.com/86924251/214131811-868f119d-c5ca-4752-b422-70e1341938a2.png)

Below is a comparison of FrameView's PCL metric vs. the ``MsInputLatency`` formula. As you can see, it is quite similar, except that there is an offset, but the overall shape of the graph seems to be the same for any CSV I have thrown at this experiment.

![image](https://user-images.githubusercontent.com/86924251/214132269-60e689d4-81f1-47f6-ba40-a6a874d0e100.png)
![image](https://user-images.githubusercontent.com/86924251/214133384-12a5e039-c462-4e2b-8703-01041a378f6f.png)

Tool to visualize the ``MsPCLatency`` column in a CSV: https://boringboredom.github.io/tools/#/RLA

**Comment by JeffersonMontgomery-Intel** [comment]
The "Measuring Application Latency" equation is actually closer to "PC Latency" than "Game Latency": it includes driver, queue, render, and composite.  I'm not sure what FrameView is doing exactly, but a likely reason for the difference is that PresentMon does not currently measure user input, which can be up to a frame sooner. 

There is more discussion here: https://github.com/GameTechDev/PresentMon/issues/106

**Comment by amitxv** [comment]
The difference is almost always exactly the same for me so whatever it is, user input as you suspected, must be quite consistent throughout the benchmark. Here is a sample CSV log from FrameView if you would like to check it. Notice the MsPCLatency column.

**Comment by amitxv** [comment]
Accidently closed. The difference is almost always exactly the same for me so whatever it is, user input as you suspected, must be quite consistent throughout the benchmark. Here is a sample CSV log from FrameView if you would like to check over it. Notice the MsPCLatency column.

[frameview-sample.csv](https://github.com/GameTechDev/PresentMon/files/10485607/default.1.csv)
