### ISSUE TITLE
CSV log unsuccessful on windows 10 anyone know how to fix it??

### ISSUE THREAD

**Issue by DB2555** [GameTechDev/PresentMon#131]
I need a fix for this issue I have been experimenting but nothing seems to work...

**Comment by DB2555** [comment]
This is the error : 
![image](https://user-images.githubusercontent.com/126919436/223790888-b78e4fcb-f411-4843-8982-3505f6969624.png)

**Comment by JeffersonMontgomery-Intel** [comment]
Does it work calling PresentMon directly instead of via AutoGpuAffinity?

**Comment by DB2555** [comment]
Ill test it (thanks for replying) also how do you call PresentMon directly? Sorry I am new to this... :)

**Comment by DB2555** [comment]
Thanks so much for replying was not sure if you would...

**Comment by DB2555** [comment]
I think I figured how to open it directly - is this it? Also when I try to open the .exe (as an administrator) it closes on launch. I'm not sure if I am opening it correctly though or even if that is how you call PresentMon directly.
![image](https://user-images.githubusercontent.com/126919436/223796853-9377a829-542c-4d1f-b97d-bad6d97d06b0.png)

**Comment by DB2555** [comment]
@JeffersonMontgomery-Intel 

How do I open PresentMon Directly??

**Comment by DB2555** [comment]
Can anyone help me @JeffersonMontgomery-Intel , @HugoLamarche , @hkaimio , @jdm3

**Comment by DB2555** [comment]
Sorry to bother I am just so stuck right now…

**Comment by JeffersonMontgomery-Intel** [comment]
Yes, you should be able to download a binary from the releases page, and then just run it (double-click etc.): https://github.com/GameTechDev/PresentMon/releases/latest  I just tried this on Win10 and it worked for me.  If it is exiting right away for you, it might be useful to know the exit code.  e.g., run from a shell and echo %errorlevel% afterwards.

**Comment by DB2555** [comment]
@JeffersonMontgomery-Intel How do I download a binary from the releases page is it one of the files in the assets drop-down box or is it somewhere and also do I use that 'binary' to run it in shell?

> Yes, you should be able to download a binary from the releases page, and then just run it (double-click etc.): https://github.com/GameTechDev/PresentMon/releases/latest I just tried this on Win10 and it worked for me. If it is exiting right away for you, it might be useful to know the exit code. e.g., run from a shell and echo %errorlevel% afterwards.

**Comment by DB2555** [comment]
@JeffersonMontgomery-Intel Please help me I am quite stuck...

**Comment by DB2555** [comment]
Can anyone help me please? @JeffersonMontgomery-Intel

**Comment by JeffersonMontgomery-Intel** [comment]
Yes, download one of the .exe files from the assets section.

To run:
1. windows button
2. cmd
3. cd downloads (or where ever you downloaded to)
4. PresentMon-1.8.0-x86.exe
5. echo %errorlevel%

If PresentMon doesn't actually terminate right away, then hit ctrl+c to get it to exit.

**Comment by DB2555** [comment]
Thank you for your help @JeffersonMontgomery-Int but how exactly do I type it into cmd?  this pops up: 
![image](https://user-images.githubusercontent.com/126919436/223867165-1fb436f8-4249-4be4-9aec-2249bcb57d14.png)
el

**Comment by DB2555** [comment]
![image](https://user-images.githubusercontent.com/126919436/223867450-64bbc9c7-1447-4a7f-8d5b-8581d20ee933.png)

**Comment by DB2555** [comment]
> Yes, download one of the .exe files from the assets section.
> 
> To run:
> 
> 1. windows button
> 2. cmd
> 3. cd downloads (or where ever you downloaded to)
> 4. PresentMon-1.8.0-x86.exe
> 5. echo %errorlevel%
> 
> If PresentMon doesn't actually terminate right away, then hit ctrl+c to get it to exit.

What do you mean by cd downloads? is cd a command or something in the command prompt?

**Comment by JeffersonMontgomery-Intel** [comment]
Yes, cd is a command.  You need to hit ENTER after each command.

**Comment by DB2555** [comment]
> Thank you for your help @JeffersonMontgomery-Int but how exactly do I type it into cmd? this pops up:
> ![image](https://user-images.githubusercontent.com/126919436/223867165-1fb436f8-4249-4be4-9aec-2249bcb57d14.png)
> el

See here, I am not sure how to type the full thing into cmd…

**Comment by DB2555** [comment]
PS. the PresentMon.exe is in my downloads folder.

**Comment by DB2555** [comment]
Please help I am not too sure what you meant by the steps.. @JeffersonMontgomery-Intel

**Comment by JeffersonMontgomery-Intel** [comment]
```bat
> cd c:\users\biju\downloads
> PresentMon-1.8.0-x64.exe
> echo %errorlevel%
```

**Comment by DB2555** [comment]
Thank you very much and thanks for your patience with me I know your a busy man but I have been struggling with this.. Thank you again let me see if it works when I open PresentMon directly.

**Comment by DB2555** [comment]
Okay I have just tried it, no error I don't think unless this means something else...

![image](https://user-images.githubusercontent.com/126919436/224076520-9a21eca7-c91e-4393-9650-ef7ed44d96bd.png)

**Comment by DB2555** [comment]
@JeffersonMontgomery-Intel What is the next step? Because at the start of our conversation you said 'Does it work calling PresentMon directly instead of via AutoGpuAffinity?' And from the screenshot above I am pretty sure it does so now what??

**Comment by DB2555** [comment]
@JeffersonMontgomery-Intel What is the next step? Because at the start of our conversation you said 'Does it work calling PresentMon directly instead of via AutoGpuAffinity?' And from the screenshot above I am pretty sure it does so now what??

> Does it work calling PresentMon directly instead of via AutoGpuAffinity?

**Comment by DB2555** [comment]
Hmm, very weird - now that I try to open PresentMon directly by double clicking the .exe it does run either way there is no error when I open it directly but there is when I run it through Auto Gpu Affinity... Anyone know a fix for PresentMon not being able to log through AutoGpuAffinity?? @JeffersonMontgomery-Intel @HugoLamarche @hkaimio @jdm3

**Comment by DB2555** [comment]
![image](https://user-images.githubusercontent.com/126919436/224080640-095290d7-85a1-41ab-8ad1-9924a2603d72.png)

**Comment by JeffersonMontgomery-Intel** [comment]
Yes, looks like it is working as expected.

I suspect this is not a PresentMon issue, so maybe you could start an issue with AutoGpuAffinity to see if they can help determine why it's failing from their environment.

**Comment by DB2555** [comment]
I have, but it seems they don't know a fix either so that is why I came here... @JeffersonMontgomery-Intel

**Comment by DB2555** [comment]
@jdm3

**Comment by DB2555** [comment]
What do you think? @JeffersonMontgomery-Intel @jdm3

**Comment by JeffersonMontgomery-Intel** [comment]
There is so far no indication this is a PresentMon issue.  I suggest that you bring this new information to them (that you can successfully run presentmon outside of their script) and see if they are willing to help you.

I'm going to close this issue now.  You will still be able to refer to it.  You may re-open it if you have new information that PresentMon is not working correctly.

**Comment by DB2555** [comment]
@JeffersonMontgomery-Intel @jdm3 WAIT!

**Comment by DB2555** [comment]
It may be a problem with the lava triangle or something... Look at this log, there are errors...

**Comment by DB2555** [comment]
![image](https://user-images.githubusercontent.com/126919436/224084906-1245712e-162a-41c5-928a-5f711552527b.png)
