### ISSUE TITLE
Potential Memory Leak

### ISSUE THREAD

**Issue by dotslash-Gatsby** [GameTechDev/PresentMon#132]
## Description
The presentmon process seems to taking up a large chunk of RAM and may indicate a memory leak. The executable is signed by Nvidia so it may be an issue caused by interactions with the presentmon executable by Nvidia software. I wanted to go ahead and open up an issue for investigation since I wasn't able to find many references to this issue online. 

I am behind 1 patch cycle on my Nvidia drivers so I will be updating after posting this and will report back if the issue continues. 

![presentmon_mem_leak](https://user-images.githubusercontent.com/70665074/230678582-5f71c4ff-dfd9-4743-83d2-9601a8fbc38d.PNG)

## Software Information

NVIDIA Driver version at the time of writing: 531.26

Computer uptime at the time of writing: 3 days 19 hours 20 minutes.

Computer purpose: gaming and youtube

## Hardware

Windows Version 10.0.19044 Build 19044

Processor AMD Ryzen 7 3700X 8-Core Processor, 3600 Mhz, 8 Core(s), 16 Logical Processor(s)

GPU: NVIDIA RTX 3070

System Model X570 AORUS ELITE WIFI

RAM: DDR4 64 Gigs, 2 sticks dual channel

Let me know if I can provide any other helpful information to track this down.

**Comment by dotslash-Gatsby** [comment]
Following up on this post one day later. I have installed the latest drivers and rebooted the system. I am still seeing presentmon grow in size over time. At the time of writing its at 3.5 gigs of memory usage..

**Comment by JeffersonMontgomery-Intel** [comment]
What version of PresentMon is this, and how are you running it?

**Comment by dotslash-Gatsby** [comment]
Apologies for the delay in response, I will grab the version of PresentMon after work today. 

As for how I am running it, It seems to be launched with Nvidia Gaming Overlay, specifically when I have the current refresh rate set to be visible on the screen. I cannot say _for sure_ these are correlated but doing some testing I have noticed that when I have that monitoring feature on, PresentMon memory usage grows over time.

**Comment by dotslash-Gatsby** [comment]
The version of presentmon is 1.2.4923. Its being executed from this directory `C:\Program Files\NVIDIA Corporation\FrameViewSDK\bin`

**Comment by JeffersonMontgomery-Intel** [comment]
Please contact NVIDIA for FrameView support, unless you are also seeing this behaviour with an official release here: https://github.com/GameTechDev/PresentMon/releases
