### ISSUE TITLE
PresentMon memory leak under certain conditions

### ISSUE THREAD

**Issue by agier9** [GameTechDev/PresentMon#134]
In my project, I create presentMon.exe as a child process of mine by using createProcess API and commandline is: "-stop_existing_session -output_stdout -qpc_time -session_name xxx".

when the father process crashed, presentMon's memory will grow all the time, it will be up to 1GB after one night.

**Comment by agier9** [comment]
yes, that make sense. so is there any ways to avoid this? thanks.

**Comment by JeffersonMontgomery-Intel** [comment]
I'm not sure why your application is crashing; but generally you'd want to trap any exceptions or exit signals and make sure you shut down the child presentmon process before your parent application exits.

**Comment by agier9** [comment]
thanks. we find a proper way to ensure presentMon exit when its parent process crashed.
