### ISSUE TITLE
Github source versus latest Intel release?

### ISSUE THREAD

**Issue by aggieNick02** [GameTechDev/PresentMon#141]
What is the state of this Github repo compared to the binaries distributed in the official Intel release from today at https://game.intel.com/story/intel-presentmon/ ?

There hasn't been a commit to this repo since in 8+ months, so I'm curious if the source for the new official Intel releases is open and in another repo, or if there is some other arrangement?

**Comment by markgalvan-intel** [comment]
Hello there! This is the current repository for PresentMon. Unfortunately, we encountered a logistical hiccup that prevented us from updating the repository with the most recent source code. We're committed to resolving this, and we'll refresh the repository with the latest code early next week. This code aligns with the release available at https://game.intel.com/story/intel-presentmon/. Apologies for any confusion this may have caused!

**Comment by aggieNick02** [comment]
Ah, ok, thanks for the info. That's great to hear.

Excited to learn more about the work y'all have been doing in the latest release with GPUBusy.
