### ISSUE TITLE
Graph height not dynamically (re/de)scaling

### ISSUE THREAD

**Issue by Ramontique** [GameTechDev/PresentMon#145]
The height of the graphs doesn't dynamically (re)scale resulting in two lines almost on top of each other on the bottom of the graph:

https://i.imgur.com/HidEnXu.png

As you can see a lot of information is lost because of this.

**Comment by fdutheil** [comment]
I can confirm, as soon as a game gets a high FPS value (like >1000FPS in a menu), the scale never recover, until I restart the PresentMon.

**Comment by planetchili** [comment]
Thank you for reporting this issue. We are aware of it and working on a fix.
Duplicate of #162

**Comment by planetchili** [comment]
Duplicate of #162
