### ISSUE TITLE
Window Defender Detects Trojan

### ISSUE THREAD

**Issue by Banner-Keith** [GameTechDev/PresentMon#146]
I attempted to download and install PresentMon v0.5-beta on Windows 11.

The download url was https://intelpresentmon.s3.amazonaws.com/PMInstaller-v0.5-beta.msi

The downloaded file does not show that it was published by intel, I am assuming that this is not being signed due to being in beta. This results in Microsoft attempting to block the download.

When I bypass that and complete the download it immediately gets quarantined by Windows defender. It believes that this contains a trojan.

[Trojan:Script/Wacatac.B!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503)

I am assuming that is a false positive, but wanted to bring it to your attention.

**Comment by planetchili** [comment]
Thank you for your feedback. Originally we only signed the client application (required for rendering overlay on top of fullscreen exclusive games), but we are now signing the installer package as well.  In the next release will also sign the service.
