### ISSUE TITLE
Minecraft Java edition now shown in 'Process' dropdown

### ISSUE THREAD

**Issue by elfhunt** [GameTechDev/PresentMon#148]
I tried to monitor Minecraft Java edition (1.20.1), which was launched by Minecraft Launcher. However, PresentMon didn't detect either game itself or its VM(OpenJDK Platform binary). The 'Process' selection dropdown only presented the Minecraft Launcher, while Windows Task Manager showing Minecraft(Java VM) using GPU.
What shall I do for monitoring Minecraft with PresentMon?

![Minecraft PresentMon 0 5](https://github.com/GameTechDev/PresentMon/assets/29049500/19cc0170-bca7-49ef-a05a-7f6184d11709)

Many thanks in advance.

**Comment by Neron-png** [comment]
Can corroborate, however, a workaround using the command-line version of Presentmon (which this repository is about) is to target the specific process ID.
`.\PresentMon-1.8.0-x64.exe -process_id {javaw process ID - can be found through Task manager} -output_file output.csv`

**Comment by KingGeorg2** [comment]
Hello, presentmon can detect it if you deactivate the "target block list" option in the capture tab.
Then you can select it.
![image](https://github.com/GameTechDev/PresentMon/assets/142755469/d0082762-97a8-41cc-b194-6d7a5eb77036)
![image](https://github.com/GameTechDev/PresentMon/assets/142755469/7c6e4b70-44f1-4ee5-8932-1ca223a5bfcb)
