### ISSUE TITLE
how do i calculate 1%, 0.1% 0.01% low from the csv data?

### ISSUE THREAD

**Issue by hedihadi** [GameTechDev/PresentMon#153]
hello, sorry for this low effort question but i've tried searching, tried chatgpt and did some experiments myself but none has helped me so far. i want to know how to calculate 1%, 0.1% 0.01% low fps from the csv data, i'd really appreciate it.

i'm also attaching a sample csv file
[PresentMon-2023-08-23T135841.csv](https://github.com/GameTechDev/PresentMon/files/12418373/PresentMon-2023-08-23T135841.csv)

**Comment by JeffersonMontgomery-Intel** [comment]
If you have excel, you can use the PERCENTILE function, e.g.: `=1000/PERCENTILE(O2:O381,0.01)`

**Comment by JeffersonMontgomery-Intel** [comment]
Good description here: https://en.wikipedia.org/wiki/Percentile

**Comment by hedihadi** [comment]
> Good description here: https://en.wikipedia.org/wiki/Percentile

thanks! i used Google Sheets and used your formula. but instead of O (which is msBetweenDisplayChange) i used J (which is msBetweenPresents)
and got accurate data similar to MSI.
