### ISSUE TITLE
Unable to install PMInstaller-v0.5-beta.msi

### ISSUE THREAD

**Issue by kenthinson** [GameTechDev/PresentMon#160]
Hello! I tried PMInstaller-v0.5-beta.msi. It fails to start the installer past this message that immediately shows on opening.

![Screenshot 2023-08-28 040759](https://github.com/GameTechDev/PresentMon/assets/2245494/39a20b7e-6b46-4b2a-b562-110808cd4a44)

I have no drive H in my system at all. I do have a windows raid (drive Z) that is made up of 4 drives. Maybe the installer is incorrectly identifying one of those drives in that raid? Other then that guess I have no idea.

**Comment by markgalvan-intel** [comment]
Hello! Sorry to hear about the installation issue. Can you run the following command:
"msiexec /i PresentMon.msi /l*v PresentMonLog.txt"? This will produce a logfile of what the installer is doing. Please attach that logfile into this issue and we can see what is happening. Thank you and again sorry for the trouble!

**Comment by markgalvan-intel** [comment]
Closed due to non-activity.
