### ISSUE TITLE
PresentMon does not offer dGPU in the adapter dropdown

### ISSUE THREAD

**Issue by skeptile2** [GameTechDev/PresentMon#165]
I'm running a 7700x and a 6800xt, and the only adapter in the dropdown is the iGPU. I've tried forcing windows to use the dGPU for the presentmon application, but it doesn't change anything.

![image](https://github.com/GameTechDev/PresentMon/assets/22998324/741c34ee-a0ce-4826-9a3f-a7a6cd85606e)

**Comment by markgalvan-intel** [comment]
Hello, we have root caused the issue to be the same as: https://github.com/GameTechDev/PresentMon/issues/142

We are currently working on a fix. I will update this thread with progress.

**Comment by markgalvan-intel** [comment]
Hello @skeptile2! We have pushed a fix for this issue. Just curious if it has been resolved for you?

**Comment by skeptile2** [comment]
Yep, V2.0 and I can see both adapters in the dropdown. Thanks!

**Comment by markgalvan-intel** [comment]
Thank you!!
