### ISSUE TITLE
[bug] Selecting exited process causes PresentMon to crash

### ISSUE THREAD

**Issue by foxt** [GameTechDev/PresentMon#168]
If you have auto-select turn off, and end up having a stale process list in the drop down,  and you select a process that has exited, the PresentMon settings window will go solid white.

Hardware: Intel i7-10700k, AMD RX 6600
Software: Windows 11, PresentMon 1.9.0

**Comment by planetchili** [comment]
Thank you for reporting this issue. We will reproduce on our side and add additional checks to avoid the crash condition.

**Comment by planetchili** [comment]
Update on this, we were able to repro and fix the issue. It will be available in the next release. Thanks again for your report.
