### ISSUE TITLE
broken CPU metrics (Power, Temp, Util) on Core i5-13500

### ISSUE THREAD

**Issue by valfaun** [GameTechDev/PresentMon#174]
Hi. I decided to try out the new PresentMon tool and noticed that at least some of the CPU metrics are broken for me, namely CPU Power, CPU Temperature and CPU Utilization. Power and Temperature show no value at all while Utilization shows clearly incorrect values: 
![PresentMon_2023-09-11_02-00-19](https://github.com/GameTechDev/PresentMon/assets/31076037/31f0d851-afb6-47bc-af32-c6f461fbdc30) 
Power and Temperature are being properly read in my current RTSS + HWiNFO setup: 
![Warframe x64_2023-09-11_02-15-19](https://github.com/GameTechDev/PresentMon/assets/31076037/5d64bd09-4283-42ee-9787-2afd8234ff38) 
Interestingly enough, Corsair's iCUE software also doesn't show CPU Utilization properly, reading the same single-digit values that PresentMon sees

**Comment by DevTechProfile** [comment]
There is already a PR addressing the CPU load issue. Just for your info. 

https://github.com/GameTechDev/PresentMon/pull/167

**Comment by valfaun** [comment]
> There is already a PR addressing the CPU load issue. Just for your info.
> 
> #167

Ah, so that one's on Microsoft, good to know. Sorry, I've never really interfaced with github beyond downloading stuff, so I didn't know where to look for existing information. Thank you for the reply

**Comment by Kaldaien** [comment]
Regarding temperature and power consumption, there is no standard WMI data provider that produces that information.

In Special K, I wrote my own kernel driver to get that information directly from the CPU (and it has code specific to Intel and AMD processors and pretty unlikely PresentMon would write such a thing). That's pretty much what all HW monitoring software on Windows does since nothing that comes standard with Windows, or even software chipset drivers, produces this data for WMI.

**Comment by markgalvan-intel** [comment]
@Kaldaien wonderful synopsis of what needs to be done to capture CPU telemetry. We originally explored going down this path but stopped when we started to realize the effort and support requirements. We have not completely abandoned the idea but we are trying to come up with the right balance for the CPU telemetry. We are however going to clean up the way we report back telemetry so users know exactly what is available and what is not. We know the current method is confusing to the user and will make it better.

With regards to your PR (https://github.com/GameTechDev/PresentMon/pull/167) I have merged the changes into our internal repo and it will be available in the next Intel PresentMon release. Great stuff and appreciate the contribution very much!

**Comment by valfaun** [comment]
> @Kaldaien wonderful synopsis of what needs to be done to capture CPU telemetry. We originally explored going down this path but stopped when we started to realize the effort and support requirements. We have not completely abandoned the idea but we are trying to come up with the right balance for the CPU telemetry. We are however going to clean up the way we report back telemetry so users know exactly what is available and what is not. We know the current method is confusing to the user and will make it better.
> 
> With regards to your PR (#167) I have merged the changes into our internal repo and it will be available in the next Intel PresentMon release. Great stuff and appreciate the contribution very much!

I see. So there's no current plan to support CPU metrics then. Unfortunate for me, I was really hoping PresentMon would become my 1-stop-shop for relevant hardware monitoring, but I understand if GPU-related metrics are the focus for now. Maybe Microsoft will add native support for such hardware telemetry in the future, though I'm not holding my breath for that

**Comment by Saffsanity** [comment]
Would be nice to pass the metrics from HWiNFO into the PresentMon overlay (similar to how Riva does it), at least until there is native telemetry.
