### ISSUE TITLE
 How to read the .csv files

### ISSUE THREAD

**Issue by mikaelbrun** [GameTechDev/PresentMon#18]
This is not an issue exactly, but I couldn't pull a request.

I have recorded and logged some action, but I don't find the FPS numbers. 
Could you give some instructsions on how to obtain those out of the .csv file?

**Comment by jenatali** [comment]
The MsBetweenPresents column is your frame time measured on the CPU in milliseconds. In other words, it's ms/frame. To transform that into frames/second, you invert it (1 / value) and then multiply by 1000, which is 1000/<MsBetweenPresents value>.
