### ISSUE TITLE
Doesn't detect D3D9 Vsync state

### ISSUE THREAD

**Issue by vlad54rus** [GameTechDev/PresentMon#182]
PresentMon reports SyncInterval=0 even when Vsync is enabled in the game.
![Screenshot](https://github.com/GameTechDev/PresentMon/assets/22005398/eb9e1669-7dd0-4dec-bb69-f91c12094133)

**Comment by AlexUnwinder** [comment]
Isn't it by design? For Direct3D9 swap interval is not a Present call parameter, it is Direct3D device's creation parameter. So I supposed it is logical to be unable to see it per each ::Present call in such API environment.

**Comment by vlad54rus** [comment]
Looks like it only does so if G-Sync is enabled, for both D3D9 and DXGI.
