### ISSUE TITLE
how does IntelPresentmon gets the process with most GPU utilization?

### ISSUE THREAD

**Issue by hedihadi** [GameTechDev/PresentMon#189]
hello, sorry for posting it here, but there's no Discussion section and i don't know C++ or C to look into the source code. i'm trying to make a similar program to IntelPresentmon. but i cannot find any method to get a process's GPU usage to find the game's processes. how does IntelPresentmon achieves this?

**Comment by JeffersonMontgomery-Intel** [comment]
PresentMon collects a variety of Event Tracing for Windows (ETW) events to determine GPU utilization per process.

If you don't want to use PresentMon and don't know C/C++, I'd suggest trying to find an interface to Windows Performance Counters in whatever you're developing in.  e.g., you can access this from powershell `Get-Counter "\GPU Engine(*engtype_3D)\Utilization Percentage"`

**Comment by hedihadi** [comment]
that code was extremely useful @JeffersonMontgomery-Intel thank you!
