### ISSUE TITLE
"-hotkey" switch results in high CPU overhead

### ISSUE THREAD

**Issue by Chipcraft** [GameTechDev/PresentMon#19]
The hotkey implementation is currently broken. When the program is used with "-hotkey" switch the program fully consumes a single CPU core, resulting a vast CPU overhead in CPU limited scenarios. 

The issue is present during both the wait period (prior pressing the hotkey, F11) and during the actual data acquisition (after the hotkey has been pressed). The issue can be easily replicated even without running any 3D application: "PresentMon64 -process_name  anyname.exe -hotkey". The program will immediately fully consume a single CPU core. To verify it on a multicore CPU, you can set the process affinity to a single core (to see the 100% utilization).

**Comment by jdm3** [comment]
Thanks for reporting this issue.

To be clear, when you say "the hotkey implementation is currently broken" is what you mean that it has higher than expected overhead?  Or do you mean that F11 doesn't actually start/stop capture?

On my system, the hotkey seems to work and one core increases to about 70% utilization whenever -hotkey is used.  I'll start looking into this overhead.

**Comment by jdm3** [comment]
The overhead caused by -hotkey has been considerably reduced in [v1.0.0](https://github.com/GameTechDev/PresentMon/releases/tag/v1.0.0). 

Let me know if you are still seeing issues.
