### ISSUE TITLE
Crash when launching an application with non-ANSI characters in filename

### ISSUE THREAD

**Issue by malikm** [GameTechDev/PresentMon#191]
When launching a process with non-ANSI characters in filename (e.g. try to copy notepad.exe and rename it to include non-ANSI characters), PresentMon crashes in HandleProcessEvent here: https://github.com/GameTechDev/PresentMon/blob/b4695462b4f10d681a0aabc243f7aa10d5b59eff/PresentData/PresentMonTraceConsumer.cpp#L2195

Problem is that if wcstombs_s fails to convert the process name to ANSI, the resulting string size will be 0.
Best solution would be to change ImageFileName to wstring rather than a plain char string. This will also allow proper filtering of process names with non-ANSI chars.

**Comment by JeffersonMontgomery-Intel** [comment]
Thanks for debugging and reporting, we'll fix this soon.
