### ISSUE TITLE
TraceSession does not contain `mStartQpc` member

### ISSUE THREAD

**Issue by illusion0001** [GameTechDev/PresentMon#200]
On commit ba4c5c62493bd3652513357e1141f3f359664768, PresentMonService fails to build due to missing `mStartQpc` member in `TraceSession` struct.

https://github.com/GameTechDev/PresentMon/blob/ba4c5c62493bd3652513357e1141f3f359664768/PresentData/TraceSession.hpp#L7-L35
https://github.com/GameTechDev/PresentMon/blob/ba4c5c62493bd3652513357e1141f3f359664768/IntelPresentMon/PresentMonService/PresentMon.cpp#L265-L269
```
"E:\git\PresentMon\PresentMon2.sln" (default target) (1) ->
"E:\git\PresentMon\IntelPresentMon\PresentMonService\PresentMonService.vcxproj" (default target) (9) ->
  E:\git\PresentMon\IntelPresentMon\PresentMonService\PresentMon.cpp(265,22): error C2039: 'mStartQpc': is not a member
 of 'TraceSession' [E:\git\PresentMon\IntelPresentMon\PresentMonService\PresentMonService.vcxproj]
  E:\git\PresentMon\IntelPresentMon\PresentMonService\PresentMon.cpp(268,42): error C2039: 'mStartQpc': is not a member
 of 'TraceSession' [E:\git\PresentMon\IntelPresentMon\PresentMonService\PresentMonService.vcxproj]
 ```

**Comment by JeffersonMontgomery-Intel** [comment]
Fixed in e3f290148f8caaa79442b1d57f942eee5ef4551b
