### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by ziabytes** [GameTechDev/PresentMon#207]
I know the project is labeled as a windows one, but would you guys consider adding linux support and distributing it via flatpak

**Comment by StellarHarbour** [comment]
Yep, would be great tool for Linux

**Comment by GermanAizek** [comment]
> Unfortunately, this is not something our team will be able to implement nor maintain at this time.

Is it possible to make fork with porting to Linux under MIT license? Legally, I don't really understand, but copyright on fork will remain under Intel Corp

**Comment by tuxayo** [comment]
> Is it possible to make fork with porting to Linux under MIT license?

Yes, any libre/open source licence would have no restriction about a port.
