### ISSUE TITLE
PresentMon  (Windows protected your PC)

### ISSUE THREAD

**Issue by MetalKidRyzenX3D** [GameTechDev/PresentMon#208]
Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

App: | PresentMon-1.10.0-x86.exe

Publisher:  
Unknown publisher

WONT LET ME RUN IT ON WINDOWS 10 WTF??????????????

**Comment by MetalKidRyzenX3D** [comment]
and this is from an Intel engineer???? what the fuck?

**Comment by MetalKidRyzenX3D** [comment]
fuck you Intel and Gamers nexus

https://www.youtube.com/watch?v=C_RO8bJop8o

**Comment by JeffersonMontgomery-Intel** [comment]
Deleting the last comment, not appropriate or helpful to resolving this.

Windows defender will clear it eventually, but looking a bit more now I see there's ways to avoid this (https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro).  We'll incorporate a better solution for future releases.

**Comment by markgalvan-intel** [comment]
We are now signing the PresentMon capture application.
