### ISSUE TITLE
Suggestion for CSV-files capture

### ISSUE THREAD

**Issue by mbk1969** [GameTechDev/PresentMon#213]
Too many columns in CSV-file are "N/A".
I believe developers can try all columns beforehand to exclude "N/A" ones from CSV-file.

Like:
- populate list with column names - future first line with headers;
- poll each column counter one time;
- exclude "N/A" columns from list (and from future polling), write list to CSV-file;
- proceed with all "Available" columns.

**Comment by markgalvan-intel** [comment]
Thank you for your valuable feedback. After careful consideration, we have opted to maintain our current approach of utilizing 'N/A' to indicate the availability status of a metric within the system.
