### ISSUE TITLE
GPU and CPU wait not available

### ISSUE THREAD

**Issue by sllnnx** [GameTechDev/PresentMon#215]
I could not find, for the life of me, the GPU/CPU wait metrics in the current version of PresentMon, nor in the upcoming release. I saw it being showcased in a Youtube video: https://www.youtube.com/watch?v=C_RO8bJop8o what is the status?
I have a Ryzen 7 7800X3D on a 4080s.

**Comment by mbk1969** [comment]
@sllnnx  Video was showing future release of PresentMon. It is still no available for download.

**Comment by markgalvan-intel** [comment]
Apologies for the delay in the release. We have posted the latest here: https://github.com/GameTechDev/PresentMon/releases/tag/v2.0.0

Thank you for your patience!
