### ISSUE TITLE
Cannot read process World of Warcraft correctly

### ISSUE THREAD

**Issue by alarchy** [GameTechDev/PresentMon#218]
World of Warcraft classic client (WowClassic.exe) v 1.15.2.54067. Overlay will pull data from launch to character select, continue to work while loading, but as soon as the character is logged in all statistics stop and cannot be restarted. 

Nvidia GTX 1660 Ti, driver 546.17

Have tried:
- closing and re-opening PresentMon
- repeatedly using the overlay hotkey to disable/enable overlay
- selecting the executable instead of using auto detection
- reducing the amount of statistics collected

![image](https://github.com/GameTechDev/PresentMon/assets/6404404/153e031f-73d9-47ae-8d58-4d8d79676270)

**Comment by markgalvan-intel** [comment]
Thank you for reporting the issue. We'll take a look.

**Comment by markgalvan-intel** [comment]
Closed with 46c51fa
