### ISSUE TITLE
CPUBusy always shows up as equal to FrameTime

### ISSUE THREAD

**Issue by Rebl11** [GameTechDev/PresentMon#222]
As the title says, CPUBusy always shows up as equal to the frame time, even when fully GPU bound. Tested in EA WRC, CP2077 and Horizon: Forbidden West. CPU is a Ryzen 9 5900X.
Is this a compatibility issue or something? I ran PresentMon as an Administrator just in case but I'm not sure why it's happening.

![image](https://github.com/GameTechDev/PresentMon/assets/166141851/33b3506a-8ce4-4527-bcb6-6e053e2b079e)

**Comment by AlexUnwinder** [comment]
CPUBusy IS frametime (minus time spent inside Present() call, which is close to zero in majority of cases when the call is non-blocking). IMHO it was really bad idea to use CPUBusy/CPUWait naming scheme for those metrics. Most of end users will never understand that CPUWait is old msInPresentAPI and CPUBusy is approximately equal to old msBetweenPresents-msInPresentAPI.

**Comment by Rebl11** [comment]
Hmm, interesting. This is not what I saw in Gamers Nexus video with Tom Petersen discussing frametimes and showing off PresentMon 2. CPU Busy/Wait seems to work how I think it should work in the video where CPUBusy + CPUWait = Frametime = GPUBusy because in that case it's a GPU bound scenario. If I'm wrong, that's okay and hopefully the new video coming out specifically about PresentMon 2 will provide further context.

**Comment by JeffersonMontgomery-Intel** [comment]
Yes, AlexUnwinder is right: CPUBusy isn't yet a measure of CPU work/utilization, but just the portion of the CPU timeline associated with that frame.  The data in your picture looks expected.

I agree the naming is currently non-ideal, but there was a desire to have consistent naming across cpu/gpu/display, and we do hope to transition the CPUBusy metric to measuring actual work in the future.

**Comment by AlexUnwinder** [comment]
That's what you saw in GN video, you just misinterpreted TAP's slide and new CPUBusy/CPUWait meterics. CPUBusy + CPUWait = frametime. CPUBusy is a time since render thread finished presenting the previous frame (i.e. returned from the previous present() call and started working on new frame) till it started presenting current frame (i.e. called present() for it). It is a _not_ total time CPU was actively working on a frame, as many users can assume from the name. CPUWait is not a total time CPU was idling during working on this frame either. It is just a wait during present() call stage, it is old msInPresentAPI metric as is. You can still use CPUWait to detect some edge cases when some blocking waiting is performed there (e.g. when Present() call is blocking due to VSync or enabled driver level or third party framerate limiter), but CPUBusy/CPUWait ratio do not allow you to see anything else.

![tap](https://github.com/GameTechDev/PresentMon/assets/55248603/a8330e14-833d-49ad-9e83-c37eebcdab5b)

**Comment by AlexUnwinder** [comment]
Oops, posted too late, sorry :)

**Comment by AlexUnwinder** [comment]
> I agree the naming is currently non-ideal, but there was a desire to have consistent naming across cpu/gpu/display, and we do hope to transition the CPUBusy metric to measuring actual work in the future.

I'm afraid it is unrealistic scenario for it to measure actual work precisely. It is possible to identify "Render" stage from TAP's slide above rather reliably via tracking the very first 3D API render submission call between two present() calls (well, at least a start of render submission stage and assume it continues till present()). But there is no way to reliably identify "Game" stage (from TAP's slide again) without receiving/hooking simulation related timings directly from the game engine. Yes, we can assume that simulation takes place on render thread and assume again that game starts it immediately after presenting and end it on render submission stage, but game's simulation can be performed on different thread, which makes our assumptions invalid.

**Comment by JeffersonMontgomery-Intel** [comment]
Yeah, I don't mean splitting "game" and "render" components like that slide, just measuring actual CPU context time much like we are currently doing for GPU.

**Comment by Rebl11** [comment]
Thanks for clarifying it. What I did see in the GN video was this:

![image](https://github.com/GameTechDev/PresentMon/assets/166141851/a4f52891-70d5-42ea-b3be-c5421fc4c9e8)
Now my question is where does that CPU Wait time come from because in this instance there shouldn't be anything actually causing the CPU to wait except for the GPU still rendering frame.

**Comment by AlexUnwinder** [comment]
GPU render queue is not infinite, full render queue may block present() call till least one frame leave it. You may try to simulate such case on your system by heavily downclocking GPU and running some GPU intensive application.

**Comment by plat2on1** [comment]
> Hmm, interesting. This is not what I saw in Gamers Nexus video with Tom Petersen discussing frametimes and showing off PresentMon 2. CPU Busy/Wait seems to work how I think it should work in the video where CPUBusy + CPUWait = Frametime = GPUBusy because in that case it's a GPU bound scenario. If I'm wrong, that's okay and hopefully the new video coming out specifically about PresentMon 2 will provide further context.

Have you tried enabling anti-lag in the AMD control panel? Seems to work as you expect in that case, still unsure what the number mean in that case though.

**Comment by Rebl11** [comment]
> 
> Have you tried enabling anti-lag in the AMD control panel? Seems to work as you expect in that case, still unsure what the number mean in that case though.

I tried it out and it now produces some CPU Wait time. If I understand correctly, without Anti-Lag/Reflex the CPU keeps pumping frames into the render queue so it's always busy.
