### ISSUE TITLE
where to find the etw event document?

### ISSUE THREAD

**Issue by chena1982** [GameTechDev/PresentMon#23]
for example, the event id:
```
enum {
        DXGIPresent_Start = 42,
        DXGIPresent_Stop,
        DXGIPresentMPO_Start = 55,
        DXGIPresentMPO_Stop = 56,
    };
```

and the event's user data struct:
```
    case DXGIPresent_Start:
    case DXGIPresentMPO_Start:
    {
        PresentEvent event;
        event.SwapChainAddress = eventInfo.GetPtr(L"pIDXGISwapChain");
        event.SyncInterval = eventInfo.GetData<uint32_t>(L"SyncInterval");
        event.PresentFlags = eventInfo.GetData<uint32_t>(L"Flags");
        event.Runtime = Runtime::DXGI;
        event.RuntimeThread = hdr.ThreadId;
```

the member name "pIDXGISwapChain", "SyncInterval", and etc.

i can't find the document.
can you tell me where i can find these info?
thanks.

**Comment by jdm3** [comment]
I don't believe these are documented, or at least I'm not aware of any documentation.

**Comment by jenatali** [comment]
I did try to find a way to dump the ETW manifest from the DLLs in the OS image, but I wasn't able to find a way to include the "template" sections which indicate what data is included in the events, just the event IDs and names. You can use the wevtutil.exe tool to get at that information.

Once you've captured an ETL trace, you can use Windows Performance Analyzer to take a look at the trace. For any events that were captured, you should be able to see (again) the event IDs as well as all of the data associated with it that WPA knows how to display.

**Comment by chena1982** [comment]
Thanks, i got it.
