### ISSUE TITLE
Please add GPUStart QPC timestamp reporting to service/console application

### ISSUE THREAD

**Issue by AlexUnwinder** [GameTechDev/PresentMon#231]
As one of possible visualization modes in my overlay I'm using dynamic colored timebands to display per-frame latencies and relative timings of different stages of rendering pipeline (you can see it in Forza Horizon 5 overlay in the very beginning of this video: https://www.youtube.com/watch?v=_uQPqLruGtg). Currently I display such timebands using the data provided by NVIDIA Reflex latency markers (it contains per-frame timestamps for start/end of each stage).

But as an alternative to it I'd like to implement something similar based purely on PresenMon's data. We already have frame "start" QPC timestamp is CPUStart. We have CPUBusy, which can be used to calculate present start timestamp. We have CPUWait, so we can calculate present end timestamp too. We have DisplayLatency, so we can also calculate display timestamp. The only missing data is GPUStart timestamp. Both GPUBusy and GPUWait are independent time intervals so we cannot reconstruct GPUStart timestamp from any existing metric. But you already have it inside the core and use it to calculate GPU metrics. So please just add GPUStart QPC timestamp reporting too, so such dynamic timabands can be visualized.

**Comment by JeffersonMontgomery-Intel** [comment]
You can use the "GPULatency" / PM_METRIC_GPU_LATENCY metric for this.

"GPULatency | How long it took from CPUStartTime until GPU work for this frame started, in milliseconds."

**Comment by AlexUnwinder** [comment]
Ah, that's it, somehow I completely missed that I can extract if from GPULatency. Attached it to prototype, seem to do exactly what I wanted to acheive:

![image](https://github.com/GameTechDev/PresentMon/assets/55248603/af3ec1c9-3c98-4a2c-adf1-05af5c102b22)

**Comment by JeffersonMontgomery-Intel** [comment]
Cool!  The intent is definitely to keep all these important measurement points exposed; the changes were supposed to be more about making the default metrics/columns more-aligned with the important values.
