### ISSUE TITLE
No stdout flush in console PresentMon 2.0. Is it intended?

### ISSUE THREAD

**Issue by AlexUnwinder** [GameTechDev/PresentMon#232]
Noticed issues with much increased data lag in scenarios when I try to read data via stdout and console PresentMon-2.0.0-x64.exe comparing to the previous console versions. I started investigating it and nailed it down to fflush(stdout), which is performed inside UpdateCsv in V1.x but missing in V2.0. Was it intended, or flushing was simply lost during refactoring? If so, can it be returned back please?

In meanwhile I solved it by building a custom version PresentMon-2.0.0-x64.exe and adding the following to the very end of UpdateCsvT:

    if (args.mCSVOutput == CSVOutput::Stdout)
        fflush(stdout);

**Comment by JeffersonMontgomery-Intel** [comment]
Thanks, this wasn't intended I'll add it back in.

**Comment by AlexUnwinder** [comment]
The issue was listed as fixed in 2.0.1, but it looks like it was not included in this version.

**Comment by JeffersonMontgomery-Intel** [comment]
It should be in 2.0.1:
- https://github.com/GameTechDev/PresentMon/commits/v2.0.1/
- https://github.com/GameTechDev/PresentMon/blob/v2.0.1/PresentMon/CsvOutput.cpp#L220

Why don't you think so -- are you still seeing this lag behaviour?

**Comment by JeffersonMontgomery-Intel** [comment]
Never mind, it's missing for non --v1_metrics metrics for some reason :( https://github.com/GameTechDev/PresentMon/blob/v2.0.1/PresentMon/CsvOutput.cpp#L326

Sorry about that, not sure how it happened, will fix asap.

**Comment by AlexUnwinder** [comment]
Sorry for bumping. Tired 2.1.0 but it seems to be missing there.

**Comment by AlexUnwinder** [comment]
Just peeked inside https://github.com/GameTechDev/PresentMon/archive/refs/tags/v2.1.0.zip and confirmed that fflush inside CsvOutput.cpp is still called for V1 metrics only. Please don't forget to include fflush for 2.0 metrics too in future versions.
