### ISSUE TITLE
PresentMon console app report lower fps after system idle for a while on AMD GPU

### ISSUE THREAD

**Issue by agier9** [GameTechDev/PresentMon#233]
running benckmark app, if we leave a while, we could got lower fps report by presentMon.

**Comment by JeffersonMontgomery-Intel** [comment]
We need more information to investigate.

What application are you measuring?

How long does the system need to be idle?

What specific metric are you referring to and how much lower does it go?

How do you know that the frame rate isn't actually decreasing after this period of idleness?

**Comment by thrower-201** [comment]
we are using either Unigine Heaven 4.0 or Dota 2.
when we have it on a multi-monitor setup, the fps reported by presentmon is always less than half the value as presented by the application.
it repro's withing a minute or 5 minutes~. 
if we use another app to record fps like Capframex / Fraps, the fps reported by them is always in sync with the fps provided by the application.

**Comment by thrower-201** [comment]
Hi @JeffersonMontgomery-Intel, any update on this?

**Comment by markgalvan-intel** [comment]
Hello, I tested this on a multi-monitored setup using an AMD Radeon RX 6700 XT and running Unigine Heaven 4.0 for more than a day and the Presented FPS AVG on the overlay followed what was displayed by the application.

When you have a chance can you provided detailed reproduction steps? Also, if you could provide system details it would be very helpful in reproducing this issue.

Thanks!

**Comment by markgalvan-intel** [comment]
Closed with these two commits:

https://github.com/GameTechDev/PresentMon/commit/1eb9691522237fbd1011132f9dd7584706576526
https://github.com/GameTechDev/PresentMon/commit/00b5ebabb2ad1838c5089285b7289842f85b8af4
