### ISSUE TITLE
PresentMon installer does not allow alternative installation paths

### ISSUE THREAD

**Issue by siberx** [GameTechDev/PresentMon#234]
The option to browse for another path is greyed out, and the disk usage dialog confirms it will take up ~500MB on my C: drive with no option to pick somewhere else to install it.

My boot drive isn't especially large, so I usually install anything non-critical to my larger secondary SSD. Why does the installer not allow installing the program to an alternative path, either on the same drive or another one?

![image](https://github.com/GameTechDev/PresentMon/assets/246440/62b57776-1a1f-4cbc-bf58-bafe854c5b2c)

**Comment by AlexUnwinder** [comment]
That's probably intentional. PresentMon's overlay is uiAccess window, which only works if application is installed into secure location like c:\program files folder.

**Comment by siberx** [comment]
Even if that is the case, wouldn't that mean _only_ the overlay needs to be installed to a "secure" location (a dubious guarantee, given that permissions can be changed for Program Files to allow it to be writable by anybody, and also that it's entirely possible to make folders on other drives admin-only writable) while the rest of the application (service, main application) should be able to reside elsewhere?

**Comment by AlexUnwinder** [comment]
We may call it a dubious guarantee, but it is Microsoft's own default requirement for uiAccess applications to work. Their OS, their rules. Unless you tweak OS, it won't work when it is installed anywhere else. Also, there is no "only the overlay" and "main application" separation in the current implementation as I see it. Main application IS overlay.

**Comment by markgalvan-intel** [comment]
Thank you for the feedback. Unfortunately, as Alex mentioned above, there is no way to accomplish this request as Intel PresentMon will not work properly if installed in a different location.
