### ISSUE TITLE
[Feature Request] show system RAM and SWAP usage

### ISSUE THREAD

**Issue by da-anda** [GameTechDev/PresentMon#236]
don't know if this is a niche feature request or not, but I would welcome to be able to see the systems RAM (and SWAP) utilization since I only have 16 GB and some games claim I have to little RAM. I also got some game crashes related to RAM, at least according to the error messages, which however were not that clear about if it was GPU RAM or system RAM, but GPU RAM seemed to be fine.

I know that there are other tools to also monitor system RAM, but it would be nice to have it all in one tool and I suppose that the metric would be rather easy to obtain. The cherry on top of it would be if in addition the RAM usage of the analyzed application could be monitored as well, but overall system RAM usage would be a great start.

Thanks much for this helpful tool, not only for professionals but also end users.

**Comment by markgalvan-intel** [comment]
Closing this issue and will track it with https://github.com/GameTechDev/PresentMon/issues/188, which we are going to use as a catch all for metric additions.
