### ISSUE TITLE
Hello, I would like to raise a question

### ISSUE THREAD

**Issue by Aletions** [GameTechDev/PresentMon#241]
About Intel PresentMon, the software sometimes fails to recognize or lose various monitoring values in the World of Warcraft Dragon Corps and Warhammer pestis II games!,This situation is difficult to reproduce, sometimes it can suddenly be unrecognizable, and sometimes it's normal！！

Can a physical memory usage monitoring be added in future versions? Thankyou!

OS: WIN10 22H2
Processor:AMD 4750G 
Memory：16G DDR4 3600
Graphics card：AMD Vega 8

**Comment by planetchili** [comment]
Hello, can we get some more details on this issue? What various monitoring values are being lost?

**Comment by Aletions** [comment]
> 您好，我们可以了解有关此问题的更多详细信息吗？哪些不同的监控值丢失了？

I thought you didn't see my question  ；）

I would like to provide feedback on whether it is possible to add some additional monitoring in future versions?
For example: 1. CPU temperature monitoring 2. Remaining amount or percentage of physical memory remaining

**Comment by markgalvan-intel** [comment]
Closing this issue and will track it with https://github.com/GameTechDev/PresentMon/issues/188, which we are going to use as a catch all for CPU metric additions.

If you are still having issues with the games mentioned above we would love to get more details.
