### ISSUE TITLE
Vcpkg 1.10.x miss file GpuTrace.hpp

### ISSUE THREAD

**Issue by cdjzzzz** [GameTechDev/PresentMon#247]
I use Vcpkg to implement PresentMon, when compiling , is report error like couldn't open file "GpuTrace.hpp": No sucn file or directory
at PresentMonTraceConsumer.hpp

**Comment by JeffersonMontgomery-Intel** [comment]
GpuTrace.hpp should be in the same directory as PresentMonTraceConsumer.hpp.  See: https://github.com/GameTechDev/PresentMon/tree/main/PresentData

Instructions for building presentmon are here: https://github.com/GameTechDev/PresentMon/blob/main/BUILDING.md

If you are having a problem with them, please post the command that is failing and the specific error(s) you are getting.

**Comment by cdjzzzz** [comment]
Yeah, I see the GpuTrace.hpp in https://github.com/GameTechDev/PresentMon/tree/main/PresentData, 
but I was not trying to build PresentMon, I just intall PresentMon vcpkg and use the package you proviede on VCPKG. I just want simply inlcude header files and link the library automately.
The problem is here,  I installed presentMon v1.10.0, but in C:\vcpkg\installed\x86-windows\include\presentmon, no GpuTrace.hpp exists.
When building the error is like this
`C:\vcpkg\installed\x86-windows\include\presentmon\PresentMonTraceConsumer.hpp(24,10): error C1083: cannot open include file: “GpuTrace.hpp”: No such file or directory`

I try to put GpuTrace.hpp into C:\vcpkg\installed\x86-windows\include\presentmon, but more linking error comes out. I was wondering that whether the packge you provide in VCPKG v1.10.0 is something wrong. OR I was using the wrong way to implement PresentMon.

By the way, v1.7.0 works fine on my side, because no GpuTrace.hpp is include in PresentMonTraceConsumer.hpp in that version.

**Comment by cdjzzzz** [comment]
Anyhow, I Successfully find a workaround to link PresentMon Vcpkg libraries.
1.Copy GpuTrace.hpp to vcpkg's installed folder, on my side is C:\vcpkg\installed\x86-windows\include\presentmon
2.Add GpuTrace.cpp into my project and compile with my CPP files.

that's it, all build error disappear.

**Comment by JeffersonMontgomery-Intel** [comment]
Thanks for the context.

We did not create nor maintain the vcpkg presentmon package.  I'm not really sure where issues should be filed, probably with https://github.com/microsoft/vcpkg?
