### ISSUE TITLE
Build Release version issues

### ISSUE THREAD

**Issue by Polarisbearkuma** [GameTechDev/PresentMon#249]
When I build the Release version, the using Microsoft.Tools is missing in the PMPreProcessor.cs file, and I've installed Extension for WIX. when building in vs, I get the error

23>D:\Software\VS2022\IDE\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: The command “Batch\post- build.bat “Release” “... \... \build\Release\” ‘PresentMon.exe’ uiAccessOn
23>D:\Software\VS2022\IDE\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: :VCEnd “Exited with code 1.
23> Completed generating project “CefNano.vcxproj” - failed.

**Comment by Polarisbearkuma** [comment]
At this point if I use the Debug configuration it can be generated successfully, but after I start CefNano, the window only shows a white background, and I'm sure that the Service that has been started, so I would also like to consult me on how to start the Debug configuration of CefNano

**Comment by Polarisbearkuma** [comment]
![window](https://github.com/GameTechDev/PresentMon/assets/59595096/ef74d584-6973-4f08-a828-3ed92a5245f7)

**Comment by Zhuya123** [comment]
Have you modified the hintpath of wix?
![image](https://github.com/GameTechDev/PresentMon/assets/39425636/918e5816-7145-4027-b65e-09afe65809b8)

**Comment by planetchili** [comment]
This issue you describe seems not to relate to WiX.

> 23>D:\Software\VS2022\IDE\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(166,5): error MSB3073: The command “Batch\post- build.bat “Release” “... ... \build\Release\” ‘PresentMon.exe’ uiAccessOn

This indicates that the post-build batch command is failing. That command primarily deploys CEF resources to their destination folders and signs the executable. Have you followed the exact steps in building.md to setup the build environment? If not, I suggest that as a first step.

As for the issue running in Debug configuration, it is possible that the executable is not able to find the web resources required for the front end. You may need to edit the Visual Studio debug configuration to specify the correct working directory (suggest setting to $(OutDir) and possible supplying command line parameters to instruct the application to load its resources from the working directory (--p2c-files-working).

**Comment by markgalvan-intel** [comment]
Closed due to inactivity. If additional help is needed, feel free to re-open.
