### ISSUE TITLE
PresentMon-v2.1.0.msi missing libcef.dll + chrome_elf.dll

### ISSUE THREAD

**Issue by tim-rex** [GameTechDev/PresentMon#254]
Installed [PresentMon-v2.1.0.msi](https://github.com/GameTechDev/PresentMon/releases/download/v2.1.0/PresentMon-v2.1.0.msi)
Upon launching I encounter an error regarding a missing _libcef.dll_

![image](https://github.com/GameTechDev/PresentMon/assets/19639392/7f4efa20-f67b-4728-946c-e64d58088afd)

I had no such issue with 2.0.1

Install directory shows as follows:
![image](https://github.com/GameTechDev/PresentMon/assets/19639392/684daabb-d973-44b4-a214-01026c720761)

It appears the installer for **2.0.1** does include libcef.dll and chrome_efl.dll
Unfortunately, while copying these into place with 2.1.0 no longer presents any errors - the application no longer starts at all

**Comment by tim-rex** [comment]
FWIW, the commandline exe works just fine

**Comment by markgalvan-intel** [comment]
Hello! Sorry to hear about the installation issue.

I just checked the install code and package and both files are present. In addition, I ran the installer on a clean machine and again both files were present and Intel PresentMon was able to run successfully.
 
We you have a free moment can you try the following?
1. Uninstall Intel PresentMon using Add/Remove programs.
2. Run the command "msiexec /i PresentMon-v2.1.0.msi /l*v PresentMonLog.txt"?

This will produce a logfile of what the installer is doing. Please attach that logfile into this issue and we can see what is happening. 
Thank you and, again, sorry for the trouble!

**Comment by TitchyGren** [comment]
I had the same issue as tim-rex after upgrading to 2.1.0 from 2.0.1.

**Comment by tim-rex** [comment]
I am now very confused...  I've uninstalled and reinstalled as instructed, and there are no longer any issues
I've attached the log in any case, though it's unlikely to reveal anything in this case

What I **can** tell you, is that I previously uninstalled via the start-menu shortcut (rather than _Add/Remove Programs_) though I wouldn't expect that to behave any differently

[PresentMonLog.txt](https://github.com/user-attachments/files/15897162/PresentMonLog.txt)

**Comment by tim-rex** [comment]
Update: I believe I have a repro..

1. Uninstall 2.1.0
2. Re-install 2.0.1
3. Start 2.0.1 and leave it open
4. Install 2.1.0 and wait for the _application in use_ warning
5. Close presentmon 2.0.1
6. Select to continue with the installer (having now closed 2.0.1)
7. Attempt to start 2.1.0
8. Observe error per description

It seems at this point, uninstalling/reinstalling 2.1.0 **will** resolve the issue (without requiring a reboot)
I've not confirmed is there is any functional difference when uninstalling via the shortcut versus _Add/Remove Programs_, hwoever I was certain I attempted this multiple times when providing this initial report (using the shortcut only)

I've attached the install log
[PresentMonLog.txt](https://github.com/user-attachments/files/15897223/PresentMonLog.txt)

**Comment by MaddyAurora** [comment]
I solved this by simply uninstalling the program (2.1.0) and reinstalling.

**Comment by markgalvan-intel** [comment]
This is great! Thank you very much for the detailed reproduction steps. Appreciate your time. I'll take a look and see if I can root cause the issue.

**Comment by planetchili** [comment]
Seems like this issue only relates to installing while PresentMon is running. We might revisit the installer processing at some point, but for now the fix is to close PresentMon before installing.

**Comment by tim-rex** [comment]
Given the installer prompts the user in the presence of a running instance ("application in use"), and has retry functionality (which evidently succeeds, and results in a broken install), it may be preferable to actively disallow the installer from proceeding at all in this scenario, and to fail with a suitable error condition.

Evidently I am not alone in having encountered this, I would not be surprised to see similar issues reported in future

**Comment by planetchili** [comment]
Thank you for the suggestion. We are currently occupied with higher-priority issues so we can't be certain when this might be addressed, but we will certainly look into a hard-fail option upon detection of a running instance the next time we revisit the WiX installer subsystem.

**Comment by farnoy** [comment]
FYI, had this again with 2.2.0 just now, clean uninstall followed by another install fixed it, same as before.

**Comment by planetchili** [comment]
Hi, did you see an error message stating "a referral was returned from the server"? There was a problem with how the binary was signed when 2.2.0 was uploaded and it was fixed about a couple of hours later when we realized it.

**Comment by farnoy** [comment]
No, I meant the missing libcef.dll issue.
