### ISSUE TITLE
Add RAM usage Widget

### ISSUE THREAD

**Issue by MaddyAurora** [GameTechDev/PresentMon#255]
There should be something as basic as CPU Memory Size Used, aka RAM usage.

**Comment by planetchili** [comment]
Thanks you for the suggestion! We have no plans on adding this functionality in the near future, but we will keep it in mind for future enhancements.

**Comment by markgalvan-intel** [comment]
Closing this issue and will track it with #188, which we are going to use as a catch all for CPU metric additions.
