### ISSUE TITLE
CPU temp widget missing, Version 2.1

### ISSUE THREAD

**Issue by MajinKayn** [GameTechDev/PresentMon#257]
maybe other widgets missing aswell
GPU 3070TI - CPU i9-14900k
![image](https://github.com/GameTechDev/PresentMon/assets/117124095/5b20e94e-f091-449c-899d-6b1171fed230)

**Comment by RodroG-85** [comment]
If I remember correctly, the widget is not missing. It was never available or implemented before. It's a requested app enhancement, though (#220 ).

**Comment by MajinKayn** [comment]
> If I remember correctly, the widget is not missing. It was never available or implemented before. It's a requested app enhancement, though (#220 ).

I saw youtube videos showing that widget and i thought the problem was mine. i'll mark this as solved, thanks for the reply.
