### ISSUE TITLE
Debug/fix sporadic GPU Wait&Latency error.

### ISSUE THREAD

**Issue by planetchili** [GameTechDev/PresentMon#267]
### Auto-migrated from intel-sandbox/applications.graphics.presentmonservice/issues/430
<sup>Original creation by JeffersonMontgomery-Intel on 2024-05-03 17:56:52+00:00</sup>

Observed from IPM capture on bc3bcc1d5b5b.

![image](https://github.com/intel-sandbox/applications.graphics.presentmonservice/assets/33905536/3adeb493-d651-47bf-ba8e-3a2426aadf56)
> [!NOTE]
> Comment by markgalvan-intel at 2024-05-07 21:07:10+00:00

This should be fixed with latest commit: dfd4383dc11305f5142b0b29b8a39b8efeacc11c. It addresses this bug: https://github.com/GameTechDev/PresentMon/issues/226. Do we have an ETL file that shows this issue?

> [!NOTE]
> Comment by JeffersonMontgomery-Intel at 2024-05-07 21:15:03+00:00

No I just noticed it while capturing live.  IIRC it was fairly easy to hit though (i.e., showed up in multiple rows of the capture.

> [!NOTE]
> Comment by markgalvan-intel at 2024-05-07 21:21:20+00:00

Okay. When you have a chance can you check with our main?

**Comment by planetchili** [comment]
I have not noticed this particular issue myself. Do we have some known repro scenarios to work with?

**Comment by markgalvan-intel** [comment]
I took a look that this one and verified that 6990a91e29064ee549d6399574509db82d428e81 does indeed fix this issue.
