### ISSUE TITLE
Can additional monitoring be added in future versions?

### ISSUE THREAD

**Issue by Aletions** [GameTechDev/PresentMon#329]
I would like to provide feedback on whether it is possible to add some additional monitoring in future versions?
For example: 1. CPU temperature monitoring 2. Remaining amount or percentage of physical memory remaining

**Comment by markgalvan-intel** [comment]
Hello!

Thank you for the feedback. Yes, we will definitely be adding additional CPU telemetry. However, at this time we have no concrete timeline for these to be added. I am closing this issue as we have a similar one here: #188.

Thanks!
