### ISSUE TITLE
Possibility for different processes with one batch?

### ISSUE THREAD

**Issue by MechWOLLIer** [GameTechDev/PresentMon#33]
Is it perhaps possible to implement a possibility to log different processes/games with one batch?
Right now it's only possible to log everything. This work with every game, but sometimes other processes are logged too. 

And with the Process_name or the id command, it's only possible to log one game per batch file. if you want to log a few games, you need a lot of batch files...which is quite unhandy.

**Comment by jenatali** [comment]
If you record all processes, you can trim down the resulting CSV file to just the processes that you're interested in. For example, if you use Excel to open the CSV, you can filter based on the process name or ID.

**Comment by jdm3** [comment]
I've also pushed a simple script you can use to prune out non-wanted processes from the CSV file: https://github.com/GameTechDev/PresentMon/blob/master/scripts/prune_processes.cmd 

Hopefully the extra step is acceptable.
