### ISSUE TITLE
Random crash after a long idle

### ISSUE THREAD

**Issue by cdjzzzz** [GameTechDev/PresentMon#340]
Version 2.1.1
After idling, the program will crash randomly. After idling for a long time (6-12 hours), the program will experience random crashes. The crash might occur in this code segment. I installed Presentmon through VCPKG, so I can't see the exact calling stack. After importing the CPP file, it shows up here.
![image](https://github.com/user-attachments/assets/d77c98a6-b582-40dc-9d9d-66a06f5c7312)

here is the calling Stack
![image](https://github.com/user-attachments/assets/bce67f91-c429-44bb-854b-f260cb832c55)

It may need to enter a long-term lock screen state or sleep mode, but I'm not too sure about this, but i have do this all the time

**Comment by planetchili** [comment]
Thank you for your report. It so happens that while working on an upcoming feature we have recently added coordination between the ETW callback thread and the thread that consumes ready frames from the queue.

In doing this we immediately encountered consistent crashes every time the program runs, and investigating we found the race condition that indeed exists in the section of code you show. The race condition there has been addressed, and the underlying design that allowed it to be created in the first time has also been replaces with something more robust.

In the behavior before coordination, the queue is only accessed every 100ms so the chances of a corruption of state were pretty low. I was wondering if anyone had encountered it "in the wild", so thank you again for your report.

Relates to #317
