### ISSUE TITLE
Maybe a bug in invoking UpdateReadyCount in PMTraceConsumer::AddPresentToCompletedList

### ISSUE THREAD

**Issue by otaku690** [GameTechDev/PresentMon#374]
https://github.com/GameTechDev/PresentMon/blob/f5b8b75042e494eed0c39cf5c318f6df1a5cbecf/PresentData/PresentMonTraceConsumer.cpp#L2010

Should the second argument true?
Based on comment in line 2008, it looks like we want to lock the mutex in UpdateReadyCount.

**Comment by malikm** [comment]
Looks like this was "resolved" in v2.3.0
