### ISSUE TITLE
Vulkan capture seems broken in v1.2.0

### ISSUE THREAD

**Issue by cooky451** [GameTechDev/PresentMon#40]
I'm testing the Vulkan capture with the cube.exe from the LunarG Vulkan SDK, but PresentMon v1.2.0 doesn't seem to get any presents from it - v1.1.2 works fine. (Also the new ctrl+c behavior is a bit annoying, since you don't get back into the command line?)

Sample output from v1.1.2 in case that helps:

cube.exe,6312,0x0000000000000000,Other,-1,0,0,Composed: Copy with CPU GDI,0,3.329873,8.362,8.332,0.000,0.008,16.488

**Comment by jenatali** [comment]
What OS version are you on?

**Comment by cooky451** [comment]
Windows 10 64-bit - Microsoft Windows [Version 10.0.15063]

GTX 970, driver version is 384.94

**Comment by jenatali** [comment]
Probably my fault, I probably broke something while adding Win7 support. I don't currently have any machines running the Creator's Update (they're all either opted into insider previews or running internal builds), and this particular present path has been deprecated, so I'm actually not easily able to debug/fix it...

Are you able to capture [an ETL file captured by GPUView's log.cmd](https://msdn.microsoft.com/en-us/library/windows/desktop/jj585574%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) and send it to me? I could debug it that way.

**Comment by yekrutdloc** [comment]
I can confirm that the latest build is **not** working if game mode is **activated**. I have game mode disabled, and all other capturing settings too, and PresentMon works as usual. I'll see if I can get some logs for you @jenatali, probably over the weekend.

**Comment by jdm3** [comment]
@cooky451 I think the "new ctrl+c behavior" is actually a bug that should be fixed in v1.2.1.

**Comment by cooky451** [comment]
I'm not sure why, could be FCU, could be new Nvidia drivers, could be the update - but it works now.

**Comment by jdm3** [comment]
Good enough for me! :)
