### ISSUE TITLE
(from OCAT) Blacklist of Applications

### ISSUE THREAD

**Issue by GuestJim** [GameTechDev/PresentMon#42]
I've been using OCAT for capturing frame time data, and while it previously had the ability to blacklist applications from being recorded, this feature was removed to ease keeping up with PresentMon. As explained on the OCAT page, the easiest way to see this return to OCAT would be for PresentMon to gain the feature directly. I hope that might be possible, but I've got an R script to remove unwanted entries, so at least I have a workaround.
Here's a link to the OCAT issue: [(v1.1.0.60) Blacklist seems to be ignored](https://github.com/GPUOpen-Tools/OCAT/issues/26).

**Comment by jdm3** [comment]
Can you please explain what's the use case here?

**Comment by GuestJim** [comment]
Using the -captureall option but still having some specific programs not captured. For example, PresentMon (at least when used through OCAT) will capture data on the Desktop Window Manager, Explorer, Steam, OBS, and OCAT. None of these applications would be of much interest to someone trying to record frame time data on a game though, and each could be something running in the background all the time for some people.
With a blacklist one could use the -captureall option all the time, instead of specifying the application whenever they need to record data for a new game. It would make the data capturing process easier for me at least, and I would think other game reviewers or just enthusiasts would enjoy the feature as well.

**Comment by jdm3** [comment]
OK, thanks for that -- makes sense.

This is certainly doable functionally, my only concern is what the performance overhead will be of checking the black/white list for each event during collection.

The current solution is to capture all and then prune after the fact using something like `PresentMon/scripts/prune_processes.cmd` (which is for whitelisting but would be easy to modify for blacklisting).

That said, I'll plan on implementing this to at least test the performance impact -- hopefully it's no big deal after all.

@amddb: Do you have anything in progress here?  In one of the OCAT issues you mentioned working on a pull request; I'd want to make sure we don't duplicate effort and/or any of your requirements are met by this.

**Comment by GuestJim** [comment]
Pruning I think would work fine, but then that's also what I set up with an R script (along with renaming the CSV to include the process name of the game), so I might be more inclined to accept this solution than others. Did not realize PresentMon already had a pruning capability, but I do not see how one could edit this list.

**Comment by amddb** [comment]
Hey @jdm3 I started preparing a PR for #43 (redirecting present events into separate files) but got distracted by other projects - so not much happened yet. 

I doubt that checking the blacklist / whitelist during collection would that big of an impact, considering that the lines are added to the file either way. I think performance could even improve by not writing out data that will be pruned later on.

My plan for now is to choose the correct output file [here](https://github.com/GameTechDev/PresentMon/blob/master/PresentMon/PresentMon.cpp#L192).
So if the blacklist / whitelist filters would be added somewhere [here](https://github.com/GameTechDev/PresentMon/blob/master/PresentMon/PresentMon.cpp#L177-L183), too, we could add both features seamlessly. In the end [this](https://github.com/GameTechDev/PresentMon/blob/master/PresentMon/PresentMon.cpp#L177-L179) already looks like it could be done via whitelist :)

**Comment by jdm3** [comment]
I added an "-exclude PROCESSNAME" command line argument (which can be repeated) in master and v1.3.0 that can be used to black-list processes.
