### ISSUE TITLE
(from OCAT) Ability to Generate Separate CSV files for Applications

### ISSUE THREAD

**Issue by GuestJim** [GameTechDev/PresentMon#43]
Like the blacklist request, this is another feature OCAT previously had but lost to help keep up with PresentMon updates. It previously would generate individual CSV files for every application it recorded, and name each file accordingly.
The OCAT issue for reference: [(v1.1.0.60) Single csv made when recording All Processes ](https://github.com/GPUOpen-Tools/OCAT/issues/25)

**Comment by jdm3** [comment]
-multi_csv command line argument added to master and v1.3.0 thanks to @amddb.
