### ISSUE TITLE
crash when run two instances

### ISSUE THREAD

**Issue by sherlock99** [GameTechDev/PresentMon#51]
Using "-process_id" to run two instances for two processes, then one of the PresentMon instance crash.

error: failed to query trace status (4201).
Assertion failed: EtwThreadsShouldQuit() || args.mEtlFileName, file PresentMon.cpp, line 99900000000 

how to avoid this?

**Comment by jenatali** [comment]
There's an embedded session name within PresentMon's logic. You can either:
1. Make a change to PresentMon to enable passing a session name on the command line, and then run your two instances with different session names, OR
2. Make a change to PresentMon to enable multiple -process_id command line parameters, OR
3. Run without -process_id, and then just filter the resulting CSV file.

**Comment by sherlock99** [comment]
I am not familiar with this project. In which function should I passing a name to the session？
Or where is the code of naming the session？

**Comment by jenatali** [comment]
The session is named [here](https://github.com/GameTechDev/PresentMon/blob/master/PresentMon/PresentMon.cpp#L904). The command line arguments are parsed [here](https://github.com/GameTechDev/PresentMon/blob/master/PresentMon/CommandLine.cpp#L261).

**Comment by jenatali** [comment]
Also, I just realized, someone already added support for multiple -process_id instances on the same command line.

**Comment by JeffersonMontgomery-Intel** [comment]
Yes, I'd recommend using one PresentMon v1.3.1 process with multiple -process_id arguments as a work around.  This should output one CSV file per target process. 

But, thanks for reporting the issue.  I'll look into fixing it for the next release.

**Comment by sherlock99** [comment]
Simply change session name with different strings may not work.
https://github.com/GameTechDev/PresentMon/blob/master/PresentMon/PresentMon.cpp#L904
The first instance shows STALE and then stop display infomation on the console.
