### ISSUE TITLE
SwapChainData occasionally cleared too early

### ISSUE THREAD

**Issue by aggieNick02** [GameTechDev/PresentMon#53]
The constant is declared as
`    CHAIN_TIMEOUT_THRESHOLD_TICKS = 10000, // 10 sec`
but is then used exclusively to compare against QPC differences. This means the timeout varies depending on machine, since QueryPerformanceFrequency values vary, and is significantly less than 10 seconds. This means PresentMon will give up on a chainmap after something as small as a 1 second hiccup in a game's graphics output.

**Comment by JeffersonMontgomery-Intel** [comment]
I took a quick look and only see it comparing against values from [GetTickCount64()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724411(v=vs.85).aspx) which should be in milliseconds.

Do you see it compared to QPC values somewhere in the code?

**Comment by aggieNick02** [comment]
Ah, you're right. The bug I'm seeing is that the chain data is getting cleared sometimes after a 1 second hiccup, and I thought I had tracked it to this, but indeed it is ticks and not qpc values, so that isn't the root cause. Sorry for the bad bug. I'll dig some more and get the real cause shortly. Feel free to close this one and I can file a new one when I've got the correct root cause.

Sorry for the noise.

**Comment by JeffersonMontgomery-Intel** [comment]
Really, no problem -- thank-you for filing.  Let's just keep it open if it sounds like somethings still up.

**Comment by aggieNick02** [comment]
Alright, so I understand what's going on now. The thing that prompted this was I would have lines in my csv files towards the end that didn't add up. For example, there would be two frames with a gap of about 0.6 seconds for TimeInSeconds, but the MsBetweenPresents on the second would be .074s .

What's happening is that UpdateProcessInfo_Realtime is seeing that the process exited and returning false, so our process info is removed. But then a few more events will have come in via the ETW callback for the process that has already exited, and these events will get processed after the ProcessInfo has been removed.

I'll admit this is a bit more corner-case than I originally thought, which minimizes the impact of the issue. If you wanted it fixed, I'm guessing a timeout mechanism in UpdateProcessInfo_Realtime would work (store the time termination is discovered in ProcessInfo and then return false to initiate the removal when the current time is far enough removed from the termination time). Totally understand if you'd prefer to just close as "will not fix".

**Comment by JeffersonMontgomery-Intel** [comment]
Thank-you very much for the detailed debugging.  Good to know this isn't highly impactfull, but I'll try to reproduce and look into fixing.

**Comment by aggieNick02** [comment]
You're welcome. Just FYI, I seem to hit it about 1 out of 8 times running the Ashes of the Singularity benchmark. I imagine increasing the refresh rate in UpdateProcessInfo_Realtime to something like every 100ms would make it more likely to happen, as the exited process would be caught sooner with a greater chance of ETW events still making their way through.

**Comment by JeffersonMontgomery-Intel** [comment]
I rewrote the update code for 1.4.0 to address this based on your debug and description of the problem.  Unfortunately, I was never able to reproduce this myself (it wasn't as prevalent on my PC for some reason) so I'm not 100% it's fixed, but I'm assuming so for now... :)
