### ISSUE TITLE
Consume ETW metadata from within trace files

### ISSUE THREAD

**Issue by jenatali** [GameTechDev/PresentMon#55]
When a trace is collected and run through XPerf's -merge functionality (which is done for GPUView traces), there's additional synthetic events that are injected just before the first instance of each event that is parseable on the machine doing the merge, which contains all of the metadata necessary to decode the payload of these events.

Ideally, PresentMon should be able to consume these instead of going to TDH, in order to support capturing a trace on one system, and running PresentMon on it on another system, without having to worry about the event format changing between the two.

**Comment by JeffersonMontgomery-Intel** [comment]
Merged into master, should generate a release soon just hoping to get a few more small changes in.
