### ISSUE TITLE
Redirect output

### ISSUE THREAD

**Issue by DevTechProfile** [GameTechDev/PresentMon#62]
What can I do to redirect the console output of PresentMon within a C# application? I've tried 

* ProcessStartInfo.RedirectStandardOutput = true + OutputDataReceived handler
* Nuget called ConsoleAppLauncher 
* cmd command "PresentMon64-1.3.1.exe >> outputfile.txt 2>&1".

Nothing works...

**Comment by JeffersonMontgomery-Intel** [comment]
Does it work if you run the c# app as administrator?

**Comment by DevTechProfile** [comment]
Unfortunately, running the C# app as administrator does not help.

**Comment by JeffersonMontgomery-Intel** [comment]
"PresentMon64-1.3.1.exe > outputfile.txt" from the console doesn't end up with anything in the outputfile.txt either.  I'm not sure if this is due to the way PresentMon is writing to the console, or because it is clearing it when done (and before each update).

What output are you trying to redirect?

e.g., using the -no_top argument should work (but then doesn't output much).  If you need the captured data itself, could you just use the output CSV (or maybe a command line argument that writes the CSV to stdout instead of a file)?

**Comment by DevTechProfile** [comment]
"What output are you trying to redirect?"

I would like to redirect the live data in the console, especially current fps, CPU and latency. The captured data itself (output files) do not contain CPU time infos. Is it possible to add a new column where these infos can be assigned? 

The point is, I want to use PresentMon as a service to get live data from. This would be a nice feature in addition to create protocol files.

**Comment by JeffersonMontgomery-Intel** [comment]
The console view uses all the same data that goes into the CSV.

e.g., 'MsBetweenPresents' is the time between the application's Present() calls on the CPU. (see https://github.com/GameTechDev/PresentMon#simple-columns--simple-command-line-argument)

I think a command line argument that causes the CSV to be written to stdout will work for you, you could then redirect it to your app, parse it, and collect whatever statistics you need from there.

Let me know if that sounds like a good solution.

**Comment by DevTechProfile** [comment]
> I think a command line argument that causes the CSV to be written to stdout will work for you, you could then redirect it to your app, parse it, and collect whatever statistics you need from there.
> 
> Let me know if that sounds like a good solution.

Yes, this should be a very good solution.

**Comment by DevTechProfile** [comment]
Is there any progress on implementing the new command line argument? ^^

**Comment by JeffersonMontgomery-Intel** [comment]
Sorry, not yet.  I'll try to get you something by the end of the week.

**Comment by DevTechProfile** [comment]
No problem. Thank you in advance!

**Comment by JeffersonMontgomery-Intel** [comment]
The [v1.4.0 release](https://github.com/GameTechDev/PresentMon/releases/tag/v1.4.0) includes the ```-output_stdout``` command line argument that will write the CSV to stdout.  Hopefully this works for you; and sorry for the delay.

**Comment by DevTechProfile** [comment]
Very nice. Many thanks so far, Jefferson! I will test it as soon as I can.
