### ISSUE TITLE
Option to output datetime of present, instead of TimeInSeconds since capture start

### ISSUE THREAD

**Issue by DevTechProfile** [GameTechDev/PresentMon#63]
Is it possible to write each data line (frametime) together with timestamps? I could really use it to compensate variations of the recording time interval.

Maybe you can provide an option to switch it on/off.

**Comment by jenatali** [comment]
I'm not sure what you mean. Can you clarify? There is a timestamp in the TimeInSeconds column.

**Comment by DevTechProfile** [comment]
The TimeInSeconds column is a duration relative to t=0. What I need is the date+time like DateTime.Now or DateTime.UtcNow.

**Comment by jenatali** [comment]
Ah. I'm not sure that ETW trace files have that -- their timestamp is QPC, which is relative to machine boot -- which means that if we added it, it'd only be for real-time tracing. In general, I prefer to stick to things that can be done in both.

**Comment by JeffersonMontgomery-Intel** [comment]
Yeah, I don't think it can be recovered from ETL after the fact.

Currently for realtime collection, and if you are using the [default output filename](https://github.com/GameTechDev/PresentMon#csv-file-names), then we take the datetime fairly close to the capture start time (technically it will be slightly after the capture start time, but should be within a second or so and we can fix this to be more precise if needed).  So, it may be possible to generate what you need with some post-processing (decode the filename and add it to `TimeInSeconds` column).

That said I'll leave this open as it's certainly possible to add a realtime-only option to do this automatically.  I've heard of other users making this change so it sounds generally useful.

Can you explain a little more what the core problem is you're trying to address ("compensate variations of the recording time interval")?

**Comment by DevTechProfile** [comment]
> Can you explain a little more what the core problem is you're trying to address ("compensate variations of the recording time interval")?

The problem is varying recording time. If a user presses the capture hotkey on the CapFrameX UI using a predefined recording time, the data stream (standard output stream from PresentMon) is been processed by an observer with a latency. If you set the timer to 20 seconds you may get 19 seconds. What I'am trying is to compensate this with buffers (preceded archive). But I need the timestamps to do that as much precise as possible.

**Comment by jenatali** [comment]
Maybe just use the "-timed" option on the PresentMon command line to implement your timer?

**Comment by DevTechProfile** [comment]
> Maybe just use the "-timed" option on the PresentMon command line to implement your timer?

I've tried this. Unfortunately, it's not precise enough.

**Comment by JeffersonMontgomery-Intel** [comment]
In order to synchronize the PresentMon data and the observer, would a QueryPerformanceCounter() value work as well?  Or is the date/time of day important too?

For `-timed` precision, is it that you need finer than second control, or because you're handling hotkey separately (or something else)?

**Comment by DevTechProfile** [comment]
A precision within a few seconds should be fine. So time info by hh:mm:ss would be perfect.

**Comment by DevTechProfile** [comment]
> For `-timed` precision, is it that you need finer than second control, or because you're handling hotkey separately (or something else)?

The observer and PresentMon must run all the time (runtime CapFrameX) because when PresentMon is been started right in the moment the hotkey is pressed the latency can be more than 2 seconds worst case.

**Comment by JeffersonMontgomery-Intel** [comment]
I have a change I'm working on that will add a command line argument `-qpc_time` which adds a CSV column `QPCTime` that contains the Present time (`TimeInSeconds`) in the form of a performance counter value (QueryPerformanceCounter()).  Performance counter values are consistent across processes, so this should allow you to synchronize the PresentMon data with events in your application.

Does that sound ok/sufficient?

**Comment by DevTechProfile** [comment]
Ok, using QueryPerformanceCounter I could call this from C#:

[DllImport("Kernel32.dll")]
private static extern bool QueryPerformanceCounter(out long lpPerformanceCount);

[DllImport("Kernel32.dll")]
private static extern bool QueryPerformanceFrequency(out long lpFrequency);

I think that is a proper way. Many thanks!

**Comment by DevTechProfile** [comment]
Ok, the QPC time is been added at the end of each line. It works fine. Thank you for that. One another question. A second console window will now be opened. Even if I start PresentMon from cmd command the window will be opened. It logs TID events?! How can I suppress this?

**Comment by JeffersonMontgomery-Intel** [comment]
The second console window shouldn't open if you are running the calling console window as administrator.

The TID event stuff is a mistake (the debug logging accidentally got left on in the release build) and I'll fix that today with a point release (see #65).
