### ISSUE TITLE
Console no longer (since 1.5) shows active swap chains / processes

### ISSUE THREAD

**Issue by MagielBruntink** [GameTechDev/PresentMon#65]
Instead the console shows a detailed event log. I tried the command line options that probably should change this behavior, but there seems to be no way to get the pre-1.5 console output back.

**Comment by JeffersonMontgomery-Intel** [comment]
Sorry!  This was my mistake, the debug logging accidentally got left on in the release build and I didn't notice somehow.

Should be fixed now in mainline and release [1.5.1](https://github.com/GameTechDev/PresentMon/releases/tag/v1.5.1).
