### ISSUE TITLE
Thoughts on getting new QPCTime in seconds instead of counter units?

### ISSUE THREAD

**Issue by aggieNick02** [GameTechDev/PresentMon#67]
Wanted to see what y'all thought of this; definitely can close if not desired.

@DevTechProfile wanted some stuff to be able to synchronize with PresentMon data, and the QPCTime you added lets him do that. I had a similar need a while back, so I had forked to customize and was recording the QPC time, but in seconds. That is, QPC/QPF. Some other software, as well as some stuff I've written, records time in this way. Plus then you get values in a unit that is a bit more intuitive.

Any reason to prefer the raw QPC values over converting them to seconds? If everyone preferred it, I could use the feature as well. If not, I can just maintain in my fork.

**Comment by JeffersonMontgomery-Intel** [comment]
For cross-process synchronization the counter value will be the most precise, but I agree seconds seems useful.  e.g., if you just have the .CSV after the fact, maybe even on a different system, the counter values alone don't mean much.

How about some new command line argument that changes `TimeInSeconds` from 0-based to system-qpc-counter-based (QPC/QPF)?

**Comment by aggieNick02** [comment]
That would work well too (that actually was what I originally had in my fork). You do lose a little precision, and it gets slightly worse for a really long running log (e.g. a giant double minus a tiny double). I'm not sure what to call it - maybe `no_time_normalization`? I had called it `record_absolute_time`, but that's not really accurate.  The time is 0 when the system starts.

On linux they use a double for CLOCK_MONOTONIC_RAW for a monotonic, non-skewed time source, and it is a double, so doing qpc time in seconds is comparable.

**Comment by JeffersonMontgomery-Intel** [comment]
Added `-qpc_time_s` which adds `QPCTime` column like `-qpc_time` did, but reports in seconds instead of QPC count.  Not totally sure if this works for you, so let me know if it needs tweaking.
