### ISSUE TITLE
Name of NTProcessEventStructs.hpp is wrong in PresentData.vcxproj, causing project to always think it is out of date

### ISSUE THREAD

**Issue by aggieNick02** [GameTechDev/PresentMon#68]
The only consequence is visual studio constantly prompting you about the project being out of date. We just need to rename `NTProcessEventEventStructs.hpp` (notice Event twice) in the vcxproj file to `NTProcessEventStructs.hpp`.

**Comment by JeffersonMontgomery-Intel** [comment]
Thanks for reporting!  Fixed in master.

**Comment by aggieNick02** [comment]
Awesome. Thank you!
