### ISSUE TITLE
Feature Request:  FPS counter on the APP screen

### ISSUE THREAD

**Issue by Droyk** [GameTechDev/PresentMon#7]
**You are about to read some bad English. and I am really sorry about it. I am not a native English speaker.**
Hey developer thanx for creating this FPS monitoring tool for UWP
but for me actually it is not really that useful because I want too see FPS in realtime but your 
PresentMon doesn't give me that functionality and I am fully sure that 90% of users want too see the fps in realtime not on back of the screen Can you plz do something about it 
**Can you plz add a FPS Counter on the right bottom of the screen**

**Comment by punkUser** [comment]
Generalized overlays are not currently possible, particularly for UWP applications. That's a large part of the need for this tool over FRAPS in the first place. As a workaround if you have a second monitor you can put PresentMon on that to monitor in real time, or use Windowed mode in games.

The primary goal of the tool is for detailed frame presentation and smoothness analysis (for developers and others). While real-time monitoring is there for convenience, the main usage mode is still to dump data to CSV and analyze offline.

**Comment by Zero3K** [comment]
So, will this feature never be added? If so, then how about adding a parameter that makes it stay on top of other windows?

**Comment by JeffersonMontgomery-Intel** [comment]
Forcing the window on top might be doable, but have you tried OCAT, it provides a GUI and other features built on the same underlying data (https://gpuopen.com/gaming-product/ocat/).

**Comment by Zero3K** [comment]
1. Ok.
2. It doesn't work for the emulator, etc. I have tried it with and is built in C# (which I don't like programs being built in it since they take up more RAM and disk space).

**Comment by Zero3K** [comment]
What about the forcing on top or could someone add an overlay via a PR?
