### ISSUE TITLE
HSync flips should still be considered tearing

### ISSUE THREAD

**Issue by jenatali** [GameTechDev/PresentMon#70]
When an MMIOFlip's FlipEntryStatusAfterFlip is FlipWaitHSync, PresentMon will wait until an HSync DPC event comes in before considering the frame completed, which enables for more accurate timing than just assuming it completes immediately. However, an HSync is still a tearing Present, while PresentMon currently treats it the same as a VSync, which is non-tearing. We should track this metadata correctly.

**Comment by JeffersonMontgomery-Intel** [comment]
Should be fixed in master.
