### ISSUE TITLE
[Q] Input lag approximation

### ISSUE THREAD

**Issue by DevTechProfile** [GameTechDev/PresentMon#71]
We've implemented the input lag approximation. Example and download link here: https://twitter.com/CapFrameX/status/1216398182734794753

I have some questions about this. After some testing serveral games, the values seem somewhat low to us. What could be the reason for this? Can the "MsUntilDisplayed" values really be read out correctly? I thought that is not possible until now.

**Comment by jenatali** [comment]
MsUntilDisplayed tracks the time from the Present API call until the first pixels could be sent to the display. It does not account for things like blank timing (e.g. the frame completes and tears at the very bottom of the screen, meaning it's not really seen until the next scan of the display), nor does it account for any processing that happens in the display itself, which generally adds a fixed additional overhead, nor does it account for time spent processing input in keyboard/controller drivers/hardware. Measuring latency with a camera from button -> photon will have a more accurate and higher value, but generally it should be a fixed offset from the input lag approximation generated by PresentMon.

**Comment by DevTechProfile** [comment]
Many thanks.
We'll include a textbox where the user can add an offset based on their hardware.

Could you give us a default offset that you use for all the added latency?

**Comment by DevTechProfile** [comment]
Issue can be closed.
