### ISSUE TITLE
[Q] Evaluation of the quality of adaptive sync technologies 

### ISSUE THREAD

**Issue by DevTechProfile** [GameTechDev/PresentMon#72]
How can we use the data from PresentMon to evaluate adaptive sync technologies? MsBetweenDisplayChange values are apparently unsuitable for this. The graphs show an adaptive course when V-Sync and G-Sync are disabled. MsUntilDisplayed is quite high. How can this be? The values are partly over 40ms, although I have a 120Hz monitor and partly over 200 FPS depending on the game. 

Thanks, Mark

**Comment by JeffersonMontgomery-Intel** [comment]
PresentMon _should_ work as usual with adaptive sync.  Can you explain a bit more what you're seeing that's wrong?

MsUntilDisplayed is impacted mainly by render time and present queueing, and 40ms could be correct for certain GPU/app.  That said, 40ms does seem high for an app that's rendering at 200fps -- are you seeing that at the same time?

**Comment by DevTechProfile** [comment]
I don't see anything wrong, I just try to extract from the data how the sync process is behaving. Is it possible to determine if G-Sync is active or not, for example? This is not apparent from the pure course of the graph.

Related to MsUntilDisplayed, see this example: https://pastebin.com/Z2ei7ZLV
In the last line MsBetweenPresents is 8.699 and MsUntilDisplayed is 27.136. This is a relatively large spread?! What do you think?

**Comment by jenatali** [comment]
27.136 / 8.7 = 3.1, which means 3 frames queued, which is D3D's default maximum frame latency. I don't think it's possible to be 100% certain if variable refresh rates are being used.

**Comment by JeffersonMontgomery-Intel** [comment]
+1 that sounds like expected default behaviour.  See https://software.intel.com/en-us/articles/sample-application-for-direct3d-12-flip-model-swap-chains for some options here if you're developing an app.

I'm not aware of any standard way to detect variable refresh.  On Intel GPUs, there is a proprietary API that provides some info on the system's capability (see https://github.com/GameTechDev/AdaptiveSync) but you'd still have to cross-reference this with the target application's present performance you're seeing via PresentMon to see if it's hitting that path so I'm not sure how useful that would be.

**Comment by DevTechProfile** [comment]
Thanks for your answers. We will remove VRR analysis from the CapFrameX feature list when it's not possible to be 100% certain wether it's being used or not. Issue can be closed.
