### ISSUE TITLE
[Feature request] Runtime/API info

### ISSUE THREAD

**Issue by DevTechProfile** [GameTechDev/PresentMon#78]
Some users would like CapFrameX to display the runtime. Could you please integrate this? What is currently included in the CSV files is the following:

Vulkan = Other
DX12 = DXGI
DX11 = DXGI
DX9 = ?
OpenGL = Other

The DirectX versions as well as Vulkan and OpenGL cannot be distinguished.

**Comment by jenatali** [comment]
This is not possible without corresponding changes in the OS and/or runtimes.

**Comment by DevTechProfile** [comment]
Sounds complicated. I wonder how it works in with RTSS. It shows always the corret 3D API on the overlay.

**Comment by jenatali** [comment]
RTSS injects into the target process and hooks the APIs. Depending on which hook is called, that determines which API is being used. PresentMon does not inject into the target process, it listens to events that are emitted by the system. Neither Vulkan nor OpenGL emit any events. DXGI emits events, but does not indicate whether it is D3D10/11/12 being used. D3D9 emits events which can identify it uniquely. D3D8 and older do not emit any events either.

The change would either be to have different APIs emit events uniquely identifying themselves to PresentMon, or have them uniquely identify themselves to the OS and then have the OS notify PresentMon. These require coordinated driver + PresentMon + maybe OS changes.

**Comment by DevTechProfile** [comment]
Ok, thanks for your answer. Issue closed..
