### ISSUE TITLE
Include etw_list tool?

### ISSUE THREAD

**Issue by jrmuizel** [GameTechDev/PresentMon#80]
run_etw_list.cmd seems to reference etw_list tool but it's not clear where to get it from.

**Comment by JeffersonMontgomery-Intel** [comment]
etw_list is a little tool I wrote and haven't pushed anywhere.  Actually, I don't think I meant to check in run_etw_list.cmd :).  It enumerates and outputs information about providers, and I use it to generate the PresentData/*Structs.hpp files.  It's not needed to build PresentMon.

I can add the tool if you think it's useful, but for now just ignore run_etw_list.cmd.

**Comment by jrmuizel** [comment]
I think it would be useful and would appreciate it if you did add it. The documentation around ETW isn't very good and there aren't a lot of samples around so I think having more information out would help people.

**Comment by pskhodad** [comment]
Having etw_list tool will help in adding custom events to get additional details about frame.
