### ISSUE TITLE
Output stream error

### ISSUE THREAD

**Issue by DevTechProfile** [GameTechDev/PresentMon#84]
We are using the "output_stdout" option in CapFrameX to get the capture data from PresentMon. Now there is a user who has problems with CapFrameX. What we know from our logs is that CapFrameX does not get any data from PresentMon. 

Is it possible that any global settings of Windows could be responsible for this? However, we only know of this one case. So it seems to be a very rare problem.

**Comment by JeffersonMontgomery-Intel** [comment]
When you say it gets no data, does it get the CSV header but no present information?  I've seen that before when a target process name was used but didn't match for some reason. 

Otherwise, nothing springs to mind in terms of windows settings or what might be wrong.

**Comment by DevTechProfile** [comment]
Since we skip the first elements of the data stream, we do not know if at least the header is been transfered.

If even you have no ideas what this might be due to, we may have to accept the error. But as I said, it is very rare.

**Comment by JeffersonMontgomery-Intel** [comment]
OK.  Well, I'm happy to take a look if you get more information or some sort of reproducer.
