### ISSUE TITLE
Incompatibility with Windows 1709

### ISSUE THREAD

**Issue by DevTechProfile** [GameTechDev/PresentMon#87]
PresentMon is incompatible with Windows 1709. I know this version is pretty old but some gamers prefer this because of better latencies.

**Comment by JeffersonMontgomery-Intel** [comment]
Do you have more details on how it's incompatible or what the issue is?

**Comment by DevTechProfile** [comment]
The problem is that no process is detected by PresentMon. The console output is empty.

**Comment by DevTechProfile** [comment]
Is it possible to start PresentMon with special command to write a log (errors, infos etc.) file?

**Comment by jenatali** [comment]
Does it work if you use the "-simple" command line? If so, it's a problem in the ETW processing pipeline and things are getting stuck, and the next steps would be to get an ETW trace (my go-to set of instructions for that is https://nvidia.custhelp.com/app/answers/detail/a_id/3507/~/how-to-generating-an-event-trace-log-for-gpuview-to-troubleshoot-performance) which we can run through PresentMon and see why things are getting stuck.

If it doesn't work with "-simple" then I have no idea.

**Comment by JeffersonMontgomery-Intel** [comment]
It can also be useful to check if anything gets collected with "-captureall"?

There is a debug log capability that requires a define change and recompile.  See https://github.com/GameTechDev/PresentMon/blob/main/PresentData/Debug.hpp.  However, I don't think it will help with process identification as it's designed more for tracing individual presents.

**Comment by DevTechProfile** [comment]
It turned out that the user who had problems with the older Windows version was using a special custom version. Some services were deactivated to "optimize" the performance. Apparently, but this is not yet clear, a standard 1709 version does not cause any problems with PresentMon.

I apologize for the "excitement".

**Comment by JeffersonMontgomery-Intel** [comment]
No problem.  Will close for now, but reopen if you find a standard 1709 version has issues too.
