### ISSUE TITLE
Win7 support is using the wrong map

### ISSUE THREAD

**Issue by jenatali** [GameTechDev/PresentMon#91]
https://github.com/GameTechDev/PresentMon/blob/main/PresentData/PresentMonTraceConsumer.cpp#L1100

This should be `mPresentsByLegacyBlitToken`, as evidenced by the fact that that's the map which has `erase` called on it at the end of the case.

**Comment by JeffersonMontgomery-Intel** [comment]
Good catch, clearly wrong.  I'll fix this now, just looking for a test case to confirm.
