### ISSUE TITLE
Massive popping up PresentMon windows

### ISSUE THREAD

**Issue by DevTechProfile** [GameTechDev/PresentMon#94]
Here's a user with a special problem: https://www.youtube.com/watch?v=H-Aih3noZQQ&feature=youtu.be

Any ideas? The user updated Windows but it doesn't help.

**Comment by jenatali** [comment]
Looks like PresentMon is trying to self-elevate, but is not actually launching the new process elevated, and so it repeats the process. You could probably work around it by launching the original app elevated.

**Comment by JeffersonMontgomery-Intel** [comment]
Yes, that's the only thing in PresentMon I can think of.  But, the parent should exit right away and the child should be called with `-dont_restart_as_admin` so if that's it something weird is going wrong that I don't understand.

It might also be interesting to see if PresentMon does this on it's own, or only via CapFrameX.  Could CapFrameX be starting multiple processes?

**Comment by DevTechProfile** [comment]
> It might also be interesting to see if PresentMon does this on it's own, or only via CapFrameX. Could CapFrameX be starting multiple processes?

Same issue when starting PresentMon directly.

**Comment by DevTechProfile** [comment]
> Yes, that's the only thing in PresentMon I can think of. But, the parent should exit right away and the child should be called with `-dont_restart_as_admin` so if that's it something weird is going wrong that I don't understand.

`-dont_restart_as_admin` seems to help. No more popping up PresentMon windows...

**Comment by jenatali** [comment]
@JeffersonMontgomery-Intel Looks like the restarted process doesn't include `-dont_restart_as_admin`, only the original command line options. However the original instance should immediately `exit()` after the new process is started, so I have no idea how it's possible to get into a loop like this.

**Comment by JeffersonMontgomery-Intel** [comment]
Hmm, looks like your right :) Plus it only exits() after waiting for the child in order to pipe the return code through.

So, not sure why either escalation is failing or we're failing to detect we're elevated... but after that happens the endless process spawning makes sense.

I haven't been able to reproduce this so far here, but I can at least add the '-dont_restart_as_admin' on the child which should fix this.  I'll send you something to test soon.

**Comment by JeffersonMontgomery-Intel** [comment]
Can you try with the following build?  I'm hoping this fixes the recursive spawning, but it also checks some errors so the printf's may help figure out what is going wrong as well.

[PresentMon64-1.5.2_issue94test.zip](https://github.com/GameTechDev/PresentMon/files/5604849/PresentMon64-1.5.2_issue94test.zip)

**Comment by DevTechProfile** [comment]
Thanks. I asked the user to test it, no reaction yet.
